"use client";
import styles from "../owner.module.css";
type Book={title:string;author:string;category:string;language:string;price:string;stock:string;source:string;url:string;descriptionES:string;descriptionEN:string;rights:string};
const books:Book[]=[
 {title:"Teachings of the Santería Gods",author:"Ócha'ni Lele",category:"Patakines · Diloggún · Santería",language:"English",price:"Publisher retail price · verify reseller cost",stock:"Publisher lists title for sale",source:"Inner Traditions / Destiny Books",url:"https://www.innertraditions.com/books/teachings-of-the-santeria-gods",descriptionES:"Colección de más de 100 relatos, mitos e historias vinculados a los odú y los orishas dentro de la tradición de Santería. Producto editorial para estudio cultural y religioso; no sustituye instrucción iniciática.",descriptionEN:"A collection of more than 100 myths, stories, and histories connected with the odu and orishas in Santería. An educational literature product; it does not replace initiatory instruction.",rights:"AUTHORIZED COMMERCIAL EDITION ONLY"},
 {title:"Diloggún Tales of the Natural World",author:"Ócha'ni Lele",category:"Patakines · Stories · Diloggún",language:"English",price:"$16.95 public list",stock:"In stock when verified",source:"Inner Traditions / Destiny Books",url:"https://www.innertraditions.com/books/diloggun-tales-of-the-natural-world",descriptionES:"Más de 40 relatos de Santería centrados en principios espirituales de la naturaleza y la filosofía Yoruba. Adecuado para la colección de literatura y patakines de BOTANICA OCHOSI.",descriptionEN:"More than 40 Santería stories centered on spiritual principles in nature and Yoruba philosophy. Suitable for BOTANICA OCHOSI's literature and pataki collection.",rights:"ISBN 9781594774195 · AUTHORIZED EDITION"},
 {title:"The Handbook of Yoruba Religious Concepts",author:"Baba Ifa Karade",category:"Yoruba · Reference",language:"English",price:"$16.95 public list",stock:"887 listed in stock when verified",source:"Red Wheel / Weiser",url:"https://redwheelweiser.com/book/the-handbook-of-yoruba-religious-concepts-9781578636679/",descriptionES:"Introducción estructurada a conceptos religiosos Yoruba, con contexto comparativo, oraciones y prácticas descritas por el autor. Se clasifica como referencia educativa Yoruba.",descriptionEN:"A structured introduction to Yoruba religious concepts with comparative context, prayers, and practices described by the author. Classified as Yoruba educational reference.",rights:"ISBN 9781578636679 · AUTHORIZED EDITION"},
 {title:"Ojise: Messenger of the Yoruba Tradition",author:"Baba Ifa Karade",category:"Yoruba · Memoir · Priesthood",language:"English",price:"$16.95 public list",stock:"19 listed in stock when verified",source:"Red Wheel / Weiser",url:"https://redwheelweiser.com/book/ojise-9780877288817/",descriptionES:"Relato del recorrido del autor hacia el sacerdocio Yoruba, presentado como literatura religiosa y memoria de práctica y formación.",descriptionEN:"An account of the author's journey toward Yoruba priesthood, presented as religious literature and a memoir of practice and formation.",rights:"ISBN 9780877288817 · AUTHORIZED EDITION"},
 {title:"Yemaya: Orisha, Goddess, and Queen of the Sea",author:"Raven Morgaine",category:"Orisha · Yemaya · Pataki",language:"English",price:"$18.95 public list",stock:"543 listed in stock when verified",source:"Red Wheel / Weiser",url:"https://redwheelweiser.com/book/yemaya-9781578637430/",descriptionES:"Obra dedicada a Yemayá que reúne historia, relatos/patakí y perspectivas devocionales de distintas tradiciones. Debe venderse como obra del autor, no como doctrina oficial de BOTANICA OCHOSI.",descriptionEN:"A work devoted to Yemaya combining history, stories/pataki, and devotional perspectives from several traditions. Sold as the author's work, not as official BOTANICA OCHOSI doctrine.",rights:"ISBN 9781578637430 · AUTHORIZED EDITION"},
 {title:"Orishas, Goddesses, and Voodoo Queens",author:"Lilith Dorsey",category:"Orisha · African Diaspora",language:"English",price:"$18.95 public list",stock:"457 listed in stock when verified",source:"Red Wheel / Weiser",url:"https://redwheelweiser.com/book/orishas-goddesses-and-voodoo-queens-9781578636952/",descriptionES:"Exploración contemporánea de figuras femeninas y orishas dentro de diversas tradiciones religiosas africanas y de la diáspora. Se mantiene separada de literatura específicamente Lucumí.",descriptionEN:"A contemporary exploration of feminine figures and orishas across African and African-diaspora religious traditions. Kept distinct from specifically Lucumí literature.",rights:"ISBN 9781578636952 · AUTHORIZED EDITION"},
 {title:"Creative Ritual",author:"El Obatala",category:"Yoruba · Santería · Comparative",language:"English",price:"$12.95 public list",stock:"19 listed in stock when verified",source:"Red Wheel / Weiser",url:"https://redwheelweiser.com/book/creative-ritual-9780877288985/",descriptionES:"Texto comparativo que combina elementos Yoruba, Santería y tradiciones mágicas occidentales desde la perspectiva del autor. Debe etiquetarse como obra ecléctica, no como manual Lucumí autorizado.",descriptionEN:"A comparative text combining Yoruba, Santería, and Western magical traditions from the author's perspective. It must be labeled eclectic rather than an authorized Lucumí manual.",rights:"ISBN 9780877288985 · AUTHORIZED EDITION"},
 {title:"The Yoruba Domino Oracle",author:"Carlos G. Y. Poenna",category:"Divination · Yoruba · Santería",language:"English",price:"$14.95 public list",stock:"Low/out-of-stock signal · verify before listing",source:"Red Wheel / Weiser",url:"https://redwheelweiser.com/book/the-yoruba-domino-oracle-9781578631490/",descriptionES:"Guía sobre una tradición de adivinación con dominós asociada por el autor al contexto Yoruba/Santería. Inventario debe verificarse antes de publicar.",descriptionEN:"A guide to a domino divination tradition presented by the author in a Yoruba/Santería context. Inventory must be verified before publication.",rights:"ISBN 9781578631490 · AUTHORIZED EDITION"}
];
const resellerPrograms=[
 {name:"Llewellyn Worldwide · Bookseller Program",detail:"Publisher/distributor program for retailers and wholesalers worldwide. New bookseller accounts advertise 50% off and free freight on the first qualifying order; resale/tax credentials required.",url:"https://www.llewellyn.com/booksellers/"},
 {name:"Red Wheel / Weiser",detail:"Publisher catalog with current product pages, ISBNs, list prices and stock signals for Yoruba/Orisha titles. Wholesale terms must be confirmed before using list price as cost.",url:"https://redwheelweiser.com/books/religion/ethnic-tribal/"},
 {name:"Inner Traditions / Destiny Books",detail:"Publisher source for Ócha'ni Lele titles including Santería patakines and Diloggún literature. Use authorized editions and verified reseller/distributor terms only.",url:"https://www.innertraditions.com"}
];
export default function OwnerSuppliersPage(){return <main className={styles.shell}><nav className={styles.nav}><a className={styles.brand} href="/owner"><span className={styles.mark}>O</span><span className={styles.brandText}><strong>BOTANICA</strong><small>OCHOSI</small></span></a><div className={styles.navLinks}><a className={styles.ghost} href="/owner">Owner OS</a><a className={styles.primary} href="/owner/catalog">Catalog Control</a></div></nav><div className={styles.content}>
<section className={styles.hero}><div className={styles.kicker}>BOOKS · PATAKINES · LITERATURE · AUTHORIZED EDITIONS</div><h1>Literature <em>Registry.</em></h1><p>Curated Yoruba, Ifá, Lucumí and Santería literature from publisher and reseller channels. Spanish and English product descriptions are stored separately from the copyrighted book text. BOTANICA OCHOSI sells authorized editions only and never republishes protected book content.</p></section>
<div className={styles.statusStrip}><span className={styles.statusPill}>Patakines · CURATED</span><span className={styles.statusPill}>ISBN / publisher · VERIFIED</span><span className={styles.statusPill}>ES + EN descriptions · REQUIRED</span><span className={styles.statusPill}>Copyright · HARD GATE</span></div>
<section className={styles.section}><div className={styles.sectionHead}><div><span>Selected literature</span><h2>Books and patakines for reseller sourcing.</h2></div></div><div className={styles.actionGrid}>{books.map(b=><article className={styles.card} key={b.title}><div className={styles.kicker}>{b.category} · {b.rights}</div><h2>{b.title}</h2><p><strong>{b.author}</strong> · {b.language}</p><p><strong>Source:</strong> {b.source}</p><p><strong>Price evidence:</strong> {b.price}</p><p><strong>Availability:</strong> {b.stock}</p><div className={styles.productMeta}><div><strong>ES:</strong> {b.descriptionES}</div><div><strong>EN:</strong> {b.descriptionEN}</div></div><a className={styles.ghost} href={b.url} target="_blank" rel="noreferrer">Review publisher product</a></article>)}</div></section>
<section className={styles.section}><div className={styles.sectionHead}><div><span>Reseller + publisher channels</span><h2>Commercial sourcing programs.</h2></div></div><div className={styles.actionGrid}>{resellerPrograms.map(r=><div className={styles.card} key={r.name}><div className={styles.kicker}>COMMERCIAL SOURCE · PENDING ACCOUNT APPROVAL</div><h2>{r.name}</h2><p>{r.detail}</p><a className={styles.ghost} href={r.url} target="_blank" rel="noreferrer">Review commercial program</a></div>)}</div></section>
<section className={styles.section}><div className={styles.card}><div className={styles.kicker}>EDITORIAL RIGHTS GATE</div><h2>Sell the book. Do not copy the book.</h2><p>Product listings may use factual metadata, short original bilingual descriptions, ISBN, publisher-authorized cover assets and licensed marketing material. Full patakines, chapters, scans, ebooks or copyrighted excerpts are never copied into the BOTANICA catalog without explicit rights. Sacred oral material also requires cultural review before BOTANICA publishes its own educational adaptation.</p></div></section>
</div></main>}
