"use client";

import styles from "../owner.module.css";

type Supplier={name:string;market:string;region:string;focus:string;channel:string;status:"PENDING REVIEW"|"FALLBACK";priority:number;url:string;wholesaleEvidence:string;pricing:"EXPLICIT WHOLESALE"|"WHOLESALE VERIFIED · PRICE GATED"|"PUBLIC LIST PRICE · WHOLESALE BY QUOTE"|"FALLBACK";minimum?:string;priceExamples?:string[];culturalFit?:string};
type Reseller={name:string;market:string;model:string;evidence:string;url:string;fit:string};
type YorubaCategory={category:string;gate:string;products:string[]};

const yorubaCatalog:YorubaCategory[]=[
 {category:"Ifa Divination",gate:"PRACTITIONER + PROVENANCE",products:["Ikin Ifa · sacred palm nuts","Opele Ifa · divination chain","Opon Ifa · divination tray","Iroke Ifa · divination tapper","Iyerosun · divination powder · import/composition review","Agere Ifa · carved Ifa bowl","Ajere / ritual containers for Ifa implements","Cowries / owo eyo · divination components","Ifa bead sets / Ide Ifa","Practitioner bags and cases for divination tools"]},
 {category:"Orisha Tools + Implements",gate:"CULTURAL FIT",products:["Elegua / Esu implements","Ogun iron implements and miniature tool sets","Ochosi / Oshosi bow-and-arrow implements","Shango / Sango double axe / ose Sango","Oshun / Osun fans, oars and brass accessories","Yemaya / Yemoja fans and marine-symbol implements","Obatala white-metal implements","Oya ceremonial implements","Orisha bells and ritual metalwork","Hand-carved Orisha figures · provenance required"]},
 {category:"Beads + Jewelry",gate:"MATERIAL + CULTURAL FIT",products:["Ide Ifa bracelets","Orisha color bead strands","Ilekes / elekes bead necklaces","Waist beads / ileke idi","Coral-style ceremonial beads · material verification","Cowrie jewelry","Brass Orisha jewelry","Handmade beaded crowns and accessories","Beaded staffs and handles","Practitioner jewelry components for custom assembly"]},
 {category:"Natural Ritual Materials",gate:"IMPORT REVIEW REQUIRED",products:["Obi Abata · kola nut","Orogbo · bitter kola","Alligator pepper / ataare","Shea butter / ori","Palm oil / epo pupa · food/cosmetic compliance as applicable","Camwood / osun powder · botanical/import review","African black soap / ose dudu","Dried botanicals traditionally used in Yoruba practice · species-by-species review","Natural clays / ritual earths · composition and import review","Non-perishable plant-derived ritual materials · species verification"]},
 {category:"Textiles + Garments",gate:"LOW IMPORT RISK · AUTHENTICITY",products:["Aso Oke fabric","Adire indigo textiles","Ankara / wax-print ceremonial fabrics","Fila Yoruba caps","Gele headwraps","Agbada ceremonial garments","Buba and wrapper sets","White practitioner garments","Orisha-color cloth and sashes","Handwoven ritual textile accessories"]},
 {category:"Ceremonial Containers + Decor",gate:"PROVENANCE",products:["Carved wooden bowls","Covered ritual vessels","Beaded containers","Calabash / igba decorative and ritual vessels · agriculture review if untreated","Wooden stools and stands","Orisha shrine decor","Hand-carved wall art","Brass bells and decorative metalwork","Ceremonial fans","Display stands for religious implements"]},
 {category:"Music + Ceremony",gate:"MATERIAL / PROVENANCE",products:["Shekere / sekere","Agogo bells","Talking drum / dundun","Bata-style drums · construction/provenance review","Hand percussion","Drum accessories","Ceremonial rattles","Wooden rhythm instruments","Bell sets","Non-animal-derived replacement drum accessories where available"]},
 {category:"Books + Educational",gate:"RIGHTS + ACCURACY",products:["Yoruba language learning materials","Ifa history and cultural studies","Orisha reference books","Lucumi-Yoruba comparative references","Yoruba dictionaries","Academic African religion studies","Children's Yoruba cultural books","Art and textile references","Authorized prayer/song study materials · copyright review","BOTANICA OCHOSI educational guides · practitioner-reviewed before publication"]},
 {category:"Home + Devotional",gate:"CULTURAL FIT",products:["Orisha-themed candles · non-consecrated retail goods","Incense and holders","Decorative statues","Altar cloths","Offering bowls","White ceramic devotional vessels","Frames and devotional art","Orisha-color home textiles","Storage boxes for devotional items","Gift-ready devotional accessory sets"]}
];

const suppliers:Supplier[]=[
 {name:"Monzon Brothers II / Monzon Botanica",market:"Miami / Hialeah",region:"Florida, USA",focus:"Afro-Cuban · Yoruba · Lucumi · botanica distributor",channel:"Wholesale / distributor",status:"PENDING REVIEW",priority:1,url:"https://monzonbotanica.com",pricing:"PUBLIC LIST PRICE · WHOLESALE BY QUOTE",wholesaleEvidence:"Wholesale available by direct contact; public prices remain market-reference only.",priceExamples:["Cascarilla · public list $23.99","Plato esmaltado 8in · public list $3.99","Caracol de Cobo large · public list $19.99"],culturalFit:"CUBAN_LUCUMI"},
 {name:"Herramientas de Santeria",market:"Miami",region:"Florida, USA",focus:"Stainless-steel Santeria / Orisha tools",channel:"Manufacturer / wholesale",status:"PENDING REVIEW",priority:2,url:"https://herramientasdesanteria.com",pricing:"EXPLICIT WHOLESALE",minimum:"$400 minimum order",wholesaleEvidence:"Product pages publish retail and wholesale prices.",priceExamples:["Oba stainless-steel tool · retail $110 · wholesale $66"],culturalFit:"CUBAN_LUCUMI"},
 {name:"Pedro Yoruba Jewelry",market:"Miami",region:"Florida, USA",focus:"Handmade Orisha tools · stainless steel · silver · gold",channel:"Miami manufacturer / wholesale",status:"PENDING REVIEW",priority:3,url:"https://pedrojewelryyoruba.com/mayoreo",pricing:"WHOLESALE VERIFIED · PRICE GATED",wholesaleEvidence:"Dedicated mayoreo program; final B2B catalog and minimums require quote.",priceExamples:["Stainless-steel tools shown from $60","Oshun stainless-steel oars shown $70","San Lazaro crutches shown $160"],culturalFit:"CUBAN_LUCUMI"},
 {name:"Yoruba Distribuidores LLC",market:"Houston",region:"Texas, USA",focus:"Yoruba · Santeria · Espiritismo",channel:"B2B wholesale only",status:"PENDING REVIEW",priority:4,url:"https://yorubadistribuidores.com",pricing:"WHOLESALE VERIFIED · PRICE GATED",wholesaleEvidence:"Wholesale only for registered botanicas and resellers; US shipping.",culturalFit:"CUBAN_LUCUMI / YORUBA"},
 {name:"Yoruba Imports",market:"Miami Gardens",region:"Florida, USA",focus:"West African religious and cultural goods · Ifa/Orisha materials",channel:"Importer / wholesale program",status:"PENDING REVIEW",priority:5,url:"https://yorubaimports.com",pricing:"PUBLIC LIST PRICE · WHOLESALE BY QUOTE",wholesaleEvidence:"US import bridge with West African sourcing relationships and wholesale program.",priceExamples:["Opon Ife large · public list $150","Edun Ara / Sango thunder stone · public list $7","Orogbo bitter kola · public list $10","Obi Abata fresh kola nuts · public list $30"],culturalFit:"YORUBA_ISESE / IFA · Lucumi compatibility review"},
 {name:"Nigeria Yoruba / Ifa direct-source lane",market:"Nigeria",region:"West Africa",focus:"Yoruba / Ifa artisan and exporter discovery",channel:"Direct producer / artisan / exporter candidates",status:"PENDING REVIEW",priority:6,url:"https://www.alibaba.com/orisha-suppliers.html",pricing:"WHOLESALE VERIFIED · PRICE GATED",wholesaleEvidence:"Discovery only. Each exporter requires independent identity, provenance, legal-import and commercial verification.",priceExamples:["Ikin / Opele / Opon / Iroke","Beads and brasswork","Aso Oke / Adire textiles","Carved ritual implements"],culturalFit:"YORUBA_ISESE / IFA · not automatically Cuban Lucumi"},
 {name:"Babonsono Imports LLC",market:"United States",region:"New Jersey, USA",focus:"Botanica · Santeria · incense · soaps · iron pots · charms",channel:"Wholesale only B2B",status:"PENDING REVIEW",priority:7,url:"https://www.babonsono.com",pricing:"EXPLICIT WHOLESALE",minimum:"$100 minimum order",wholesaleEvidence:"Wholesale-only B2B; business credentials required.",priceExamples:["IHC Incense Sticks Sandalwood 12-pack · $10.95","IHC Incense Sticks Jasmine 12-pack · $10.95"],culturalFit:"GENERAL_BOTANICA"},
 {name:"Bulk Santeria",market:"United States",region:"USA",focus:"Traditional herbs · incense · oils · Santeria botanica goods",channel:"Wholesale only",status:"PENDING REVIEW",priority:8,url:"https://bulksanteria.com",pricing:"EXPLICIT WHOLESALE",minimum:"$250 order minimum",wholesaleEvidence:"Wholesale-only website with published pricing.",priceExamples:["Pinon de Botija / Jatropha Curcas · 16 oz · $75"],culturalFit:"GENERAL_SANTERIA"},
 {name:"Distribuidora Mas Alla",market:"United States",region:"USA",focus:"Botanica / yerberia products",channel:"Wholesale distributor",status:"PENDING REVIEW",priority:9,url:"https://www.el-masalla.com",pricing:"WHOLESALE VERIFIED · PRICE GATED",wholesaleEvidence:"Botanica wholesale distributor serving US spiritual retailers.",culturalFit:"GENERAL_BOTANICA"},
 {name:"Orisha Distributor Co.",market:"Los Angeles",region:"California, USA",focus:"Natural remedies · herbs · botanica inventory",channel:"Wholesale distributor",status:"PENDING REVIEW",priority:10,url:"https://www.orishadistributor.com/wholesale",pricing:"WHOLESALE VERIFIED · PRICE GATED",wholesaleEvidence:"Wholesale program requires seller permit; USA/Canada shipping.",culturalFit:"GENERAL_ORISHA"},
 {name:"El Viejo Lazaro",market:"Miami",region:"Florida, USA",focus:"Lucumi · Yoruba · Ocha tools and botanica goods",channel:"Wholesale / retail",status:"PENDING REVIEW",priority:11,url:"https://www.viejolazaro.com",pricing:"WHOLESALE VERIFIED · PRICE GATED",wholesaleEvidence:"Practitioner-run Lucumi supplier with wholesale and retail products.",culturalFit:"CUBAN_LUCUMI"},
 {name:"Botanica Las Americas",market:"Miami",region:"Florida, USA",focus:"Santeria · Lucumi · Orisha tools · beads · herbs · candles",channel:"Wholesale / retail",status:"PENDING REVIEW",priority:12,url:"https://botanicalasamerica.com",pricing:"WHOLESALE VERIFIED · PRICE GATED",wholesaleEvidence:"Wholesale/retail supplier for the Lucumi community.",culturalFit:"CUBAN_LUCUMI"},
 {name:"Botanica Wholesale Program",market:"USA + International",region:"Worldwide",focus:"Independent retailer and online reseller program",channel:"Wholesale / reseller program",status:"PENDING REVIEW",priority:20,url:"https://www.botanica.co/pages/wholesale",pricing:"EXPLICIT WHOLESALE",minimum:"Direct $280 · Faire $400",wholesaleEvidence:"Official wholesale program with international retail participation.",culturalFit:"GENERAL"},
 {name:"CJdropshipping",market:"International",region:"Fallback",focus:"Generic complementary products only",channel:"Dropshipping",status:"FALLBACK",priority:90,url:"https://www.cjdropshipping.com",pricing:"FALLBACK",wholesaleEvidence:"Not approved for core Cuban BOTANICA sourcing.",culturalFit:"GENERIC"},
 {name:"Zendrop",market:"USA / International",region:"Fallback",focus:"Generic complementary products only",channel:"Dropshipping",status:"FALLBACK",priority:91,url:"https://www.zendrop.com",pricing:"FALLBACK",wholesaleEvidence:"Not approved for core Cuban BOTANICA sourcing.",culturalFit:"GENERIC"},
 {name:"Spocket",market:"USA / International",region:"Fallback",focus:"Generic complementary products only",channel:"Dropshipping",status:"FALLBACK",priority:92,url:"https://www.spocket.co",pricing:"FALLBACK",wholesaleEvidence:"Not approved for core Cuban BOTANICA sourcing.",culturalFit:"GENERIC"},
 {name:"AliExpress",market:"International",region:"Fallback",focus:"Generic complementary products only",channel:"Marketplace",status:"FALLBACK",priority:99,url:"https://www.aliexpress.com",pricing:"FALLBACK",wholesaleEvidence:"Not approved for core Cuban BOTANICA sourcing.",culturalFit:"GENERIC"}
];

const resellers:Reseller[]=[
 {name:"Yoruba Distribuidores reseller network",market:"United States",model:"Registered botanicas + resellers",evidence:"Wholesale-only network for registered botanicas, religious stores and resellers.",url:"https://yorubadistribuidores.com",fit:"High · Cuban/Santeria retail channel"},
 {name:"Babonsono retail partners",market:"United States",model:"B2B stores + resellers + retailers",evidence:"Wholesale supplier requiring business credentials.",url:"https://www.babonsono.com",fit:"High · broad botanica assortment"},
 {name:"BOTANICA independent online resellers",market:"USA + Abroad",model:"Independent ecommerce reseller",evidence:"Wholesale policy welcomes independent online stores and international retailers.",url:"https://www.botanica.co/pages/wholesale",fit:"Medium · complementary branded goods"},
 {name:"Faire wholesale marketplace",market:"Worldwide",model:"Retailer marketplace",evidence:"Retailer-account wholesale discovery channel.",url:"https://www.faire.com",fit:"Medium · discovery/reseller channel"},
 {name:"Orisha Distributor retail network",market:"USA + Canada",model:"Botanicas · herb shops · naturist stores",evidence:"Wholesale retailer program requiring seller permit.",url:"https://www.orishadistributor.com/wholesale",fit:"High · specialist retail distribution"}
];

export default function OwnerSuppliersPage(){return <main className={styles.shell}><nav className={styles.nav}><a className={styles.brand} href="/owner"><span className={styles.mark}>O</span><span className={styles.brandText}><strong>BOTANICA</strong><small>OCHOSI</small></span></a><div className={styles.navLinks}><a className={styles.ghost} href="/owner">Owner OS</a><a className={styles.primary} href="/owner/catalog">Catalog Control</a></div></nav><div className={styles.content}>
<section className={styles.hero}><div className={styles.kicker}>SUPPLIER + PRODUCT INTELLIGENCE · USA FIRST · YORUBA WORLDWIDE</div><h1>Supplier <em>Registry.</em></h1><p>Miami, Hialeah and Houston remain first for Cuban Lucumi. The Yoruba catalog is organized independently by product category, with Nigeria and West Africa used for provenance-sensitive Ifa and Yoruba goods. Cultural compatibility, import legality and commercial approval remain separate gates.</p></section>
<div className={styles.statusStrip}><span className={styles.statusPill}>Cuban Lucumi · USA FIRST</span><span className={styles.statusPill}>Yoruba / Ifa · CATEGORY SELECTED</span><span className={styles.statusPill}>Nigeria · PROVENANCE GATE</span><span className={styles.statusPill}>Autonomous purchasing · LOCKED</span></div>
<section className={styles.section}><div className={styles.sectionHead}><div><span>Yoruba assortment architecture</span><h2>Selected products by category.</h2></div></div><div className={styles.actionGrid}>{yorubaCatalog.map(c=><div className={styles.card} key={c.category}><div className={styles.kicker}>{c.gate}</div><h2>{c.category}</h2><div className={styles.productMeta}>{c.products.map(p=><div key={p}>• {p}</div>)}</div></div>)}</div></section>
<section className={styles.section}><div className={styles.sectionHead}><div><span>Verified sourcing evidence</span><h2>Wholesale and sourcing candidates.</h2></div></div><div className={styles.actionGrid}>{suppliers.map(s=><div className={styles.card} key={s.name}><div className={styles.kicker}>PRIORITY {s.priority} · {s.status}</div><h2>{s.name}</h2><p><strong>{s.market}</strong> · {s.region}</p><p>{s.focus}</p><p>{s.channel}</p>{s.culturalFit&&<p><strong>Cultural fit:</strong> {s.culturalFit}</p>}<p><strong>Pricing evidence:</strong> {s.pricing}</p>{s.minimum&&<p><strong>Minimum:</strong> {s.minimum}</p>}<p>{s.wholesaleEvidence}</p>{!!s.priceExamples?.length&&<div className={styles.productMeta}>{s.priceExamples.map(item=><div key={item}>• {item}</div>)}</div>}<a className={styles.ghost} href={s.url} target="_blank" rel="noreferrer">Review verified website</a></div>)}</div></section>
<section className={styles.section}><div className={styles.sectionHead}><div><span>Distribution channels</span><h2>Reseller opportunities.</h2></div></div><div className={styles.actionGrid}>{resellers.map(r=><div className={styles.card} key={r.name}><div className={styles.kicker}>RESELLER CANDIDATE · PENDING REVIEW</div><h2>{r.name}</h2><p><strong>{r.market}</strong> · {r.model}</p><p><strong>BOTANICA fit:</strong> {r.fit}</p><p>{r.evidence}</p><a className={styles.ghost} href={r.url} target="_blank" rel="noreferrer">Review reseller channel</a></div>)}</div></section>
<section className={styles.section}><div className={styles.card}><div className={styles.kicker}>APPROVAL GATE</div><h2>Broad assortment, narrow approval.</h2><p>Catalog breadth does not imply automatic sale eligibility. Fresh botanicals, seeds, untreated woods, animal-derived materials, ingestibles and other regulated natural goods require product-specific US import/compliance review. Sacred or practitioner-specific Ifa items require provenance and practitioner review. No Supplier Agent recommendation authorizes spending or publication.</p></div></section>
</div></main>}
