"use client";

import styles from "../owner.module.css";

type Supplier = { name:string; market:string; region:string; focus:string; channel:string; status:"PENDING REVIEW"|"FALLBACK"; priority:number; url:string; wholesaleEvidence:string; pricing:"EXPLICIT WHOLESALE"|"WHOLESALE VERIFIED · PRICE GATED"|"PUBLIC LIST PRICE · WHOLESALE BY QUOTE"|"FALLBACK"; minimum?:string; priceExamples?:string[]; culturalFit?:string; };
type Reseller = { name:string; market:string; model:string; evidence:string; url:string; fit:string; };

const nigeriaProducts = [
 "Obi Abata · kola nut · Ifa/Orisha ritual supply",
 "Orogbo · bitter kola · traditional Yoruba/Orisha use",
 "Ikin Ifa · sacred palm nuts · Ifa divination equipment",
 "Opele Ifa · divination chain · practitioner equipment",
 "Opon Ifa · divination tray · practitioner equipment",
 "Iroke Ifa · divination tapper · practitioner equipment",
 "Ide Ifa / Orisha beads · practitioner and devotional jewelry",
 "Cowries / owo eyo · divination and ceremonial components",
 "Yoruba carved Orisha figures and ritual implements · provenance required",
 "Traditional Yoruba textiles, beads and non-perishable ritual accessories"
];

const suppliers: Supplier[] = [
 {name:"Monzon Brothers II / Monzon Botanica",market:"Miami / Hialeah",region:"Florida, USA",focus:"Afro-Cuban · Yoruba · Lucumi · botanica distributor",channel:"Wholesale / distributor",status:"PENDING REVIEW",priority:1,url:"https://monzonbotanica.com",pricing:"PUBLIC LIST PRICE · WHOLESALE BY QUOTE",wholesaleEvidence:"Site states wholesale purchases are available, but wholesale pricing requires direct contact. Public prices remain market-reference only.",priceExamples:["Cascarilla · public list $23.99","Plato esmaltado 8in · public list $3.99","Caracol de Cobo large · public list $19.99"],culturalFit:"CUBAN_LUCUMI"},
 {name:"Herramientas de Santeria",market:"Miami",region:"Florida, USA",focus:"Stainless-steel Santeria / Orisha tools",channel:"Manufacturer / wholesale",status:"PENDING REVIEW",priority:2,url:"https://herramientasdesanteria.com",pricing:"EXPLICIT WHOLESALE",minimum:"$400 minimum order",wholesaleEvidence:"Product pages publish retail and wholesale prices and state a $400 minimum purchase.",priceExamples:["Oba stainless-steel tool · retail $110 · wholesale $66"],culturalFit:"CUBAN_LUCUMI"},
 {name:"Pedro Yoruba Jewelry",market:"Miami",region:"Florida, USA",focus:"Handmade Orisha tools · stainless steel · silver · gold",channel:"Miami manufacturer / wholesale",status:"PENDING REVIEW",priority:3,url:"https://pedrojewelryyoruba.com/mayoreo",pricing:"WHOLESALE VERIFIED · PRICE GATED",wholesaleEvidence:"Dedicated mayoreo page says the Miami workshop supplies botanicas at wholesale pricing; final B2B catalog and minimums require quote.",priceExamples:["Stainless-steel tools shown from $60","Oshun stainless-steel oars shown $70","San Lazaro crutches shown $160"],culturalFit:"CUBAN_LUCUMI"},
 {name:"Yoruba Distribuidores LLC",market:"Houston",region:"Texas, USA",focus:"Yoruba · Santeria · Espiritismo",channel:"B2B wholesale only",status:"PENDING REVIEW",priority:4,url:"https://yorubadistribuidores.com",pricing:"WHOLESALE VERIFIED · PRICE GATED",wholesaleEvidence:"Site explicitly states WHOLESALE ONLY for registered botanicas and resellers, 300+ products and US shipping.",culturalFit:"CUBAN_LUCUMI / YORUBA"},
 {name:"Yoruba Imports",market:"Miami Gardens",region:"Florida, USA",focus:"Direct West African religious and cultural goods · plants · Ifa/Orisha materials",channel:"Importer / wholesale program",status:"PENDING REVIEW",priority:5,url:"https://yorubaimports.com",pricing:"PUBLIC LIST PRICE · WHOLESALE BY QUOTE",wholesaleEvidence:"US importer advertises a wholesale program and direct sourcing relationships with West African farmers, artists and manufacturers. Use as the preferred US import bridge for Nigerian/Yoruba goods until a Nigeria exporter passes compliance review.",priceExamples:["Opon Ife large · public list $150","Edun Ara / Sango thunder stone · public list $7","Orogbo bitter kola · public list $10","Obi Abata fresh kola nuts · public list $30"],culturalFit:"YORUBA_ISESE / IFA · requires Lucumi compatibility review"},
 {name:"Nigeria Yoruba / Ifa direct-source lane",market:"Nigeria",region:"West Africa",focus:"Authentic Yoruba and Ifa ritual materials for practitioner-reviewed Cuban Santeria / Lucumi and Ifa assortment",channel:"Direct producer / artisan / exporter candidates",status:"PENDING REVIEW",priority:6,url:"https://www.alibaba.com/orisha-suppliers.html",pricing:"WHOLESALE VERIFIED · PRICE GATED",wholesaleEvidence:"Discovery lane only. Each Nigerian producer/exporter must be independently verified for legal export, identity, provenance, commercial terms and product authenticity before approval. Marketplace verification alone is insufficient.",priceExamples:nigeriaProducts,culturalFit:"YORUBA_ISESE / IFA · NOT automatically interchangeable with Cuban Lucumi"},
 {name:"Babonsono Imports LLC",market:"United States",region:"New Jersey, USA",focus:"Botanica · Santeria · incense · soaps · iron pots · charms",channel:"Wholesale only B2B",status:"PENDING REVIEW",priority:7,url:"https://www.babonsono.com",pricing:"EXPLICIT WHOLESALE",minimum:"$100 minimum order",wholesaleEvidence:"Wholesale-only B2B supplier serving stores, resellers and retailers; requires resale certificate or business license.",priceExamples:["IHC Incense Sticks Sandalwood 12-pack · $10.95","IHC Incense Sticks Jasmine 12-pack · $10.95"],culturalFit:"GENERAL_BOTANICA"},
 {name:"Bulk Santeria",market:"United States",region:"USA",focus:"Traditional herbs · incense · oils · Santeria botanica goods",channel:"Wholesale only",status:"PENDING REVIEW",priority:8,url:"https://bulksanteria.com",pricing:"EXPLICIT WHOLESALE",minimum:"$250 order minimum",wholesaleEvidence:"Website is marked Wholesale Only and publishes product pricing.",priceExamples:["Pinon de Botija / Jatropha Curcas · 16 oz · $75"],culturalFit:"GENERAL_SANTERIA"},
 {name:"Distribuidora Mas Alla",market:"United States",region:"USA",focus:"5,000+ botanica and yerberia products · candles · oils · incense · statues",channel:"Wholesale distributor",status:"PENDING REVIEW",priority:9,url:"https://www.el-masalla.com",pricing:"WHOLESALE VERIFIED · PRICE GATED",wholesaleEvidence:"Site identifies the business as a botanica wholesale distributor serving spiritual shops, Santeria candle stores and religious retailers across the United States.",culturalFit:"GENERAL_BOTANICA"},
 {name:"Orisha Distributor Co.",market:"Los Angeles",region:"California, USA",focus:"Natural remedies · herbs · botanica inventory",channel:"Wholesale distributor",status:"PENDING REVIEW",priority:10,url:"https://www.orishadistributor.com/wholesale",pricing:"WHOLESALE VERIFIED · PRICE GATED",wholesaleEvidence:"Wholesale program requires seller permit, serves botanicas and retailers, ships USA and Canada, and quotes wholesale prices by inquiry.",culturalFit:"GENERAL_ORISHA"},
 {name:"El Viejo Lazaro",market:"Miami",region:"Florida, USA",focus:"Lucumi · Yoruba · Ocha tools and botanica goods",channel:"Wholesale / retail",status:"PENDING REVIEW",priority:11,url:"https://www.viejolazaro.com",pricing:"WHOLESALE VERIFIED · PRICE GATED",wholesaleEvidence:"Practitioner-run Lucumi supplier explicitly provides wholesale and retail products, including custom Orisha tools and crowns.",culturalFit:"CUBAN_LUCUMI"},
 {name:"Botanica Las Americas",market:"Miami",region:"Florida, USA",focus:"Santeria · Lucumi · Orisha tools · beads · herbs · candles",channel:"Wholesale / retail",status:"PENDING REVIEW",priority:12,url:"https://botanicalasamerica.com",pricing:"WHOLESALE VERIFIED · PRICE GATED",wholesaleEvidence:"Practitioner-run supplier states it sells wholesale and retail for the Lucumi community and offers 4,000+ products plus custom tools and crowns.",culturalFit:"CUBAN_LUCUMI"},
 {name:"Botanica Wholesale Program",market:"USA + International",region:"Worldwide",focus:"Independent retailer and online reseller program",channel:"Wholesale / reseller program",status:"PENDING REVIEW",priority:20,url:"https://www.botanica.co/pages/wholesale",pricing:"EXPLICIT WHOLESALE",minimum:"Direct $280 · Faire $400",wholesaleEvidence:"Official program accepts brick-and-mortar and independent online retailers in the US and abroad; international shipping available and private label starts at 500 units.",culturalFit:"GENERAL"},
 {name:"CJdropshipping",market:"International",region:"Fallback",focus:"Generic complementary products only",channel:"Dropshipping",status:"FALLBACK",priority:90,url:"https://www.cjdropshipping.com",pricing:"FALLBACK",wholesaleEvidence:"Not approved for core Cuban BOTANICA sourcing.",culturalFit:"GENERIC"},
 {name:"Zendrop",market:"USA / International",region:"Fallback",focus:"Generic complementary products only",channel:"Dropshipping",status:"FALLBACK",priority:91,url:"https://www.zendrop.com",pricing:"FALLBACK",wholesaleEvidence:"Not approved for core Cuban BOTANICA sourcing.",culturalFit:"GENERIC"},
 {name:"Spocket",market:"USA / International",region:"Fallback",focus:"Generic complementary products only",channel:"Dropshipping",status:"FALLBACK",priority:92,url:"https://www.spocket.co",pricing:"FALLBACK",wholesaleEvidence:"Not approved for core Cuban BOTANICA sourcing.",culturalFit:"GENERIC"},
 {name:"AliExpress",market:"International",region:"Fallback",focus:"Generic complementary products only",channel:"Marketplace",status:"FALLBACK",priority:99,url:"https://www.aliexpress.com",pricing:"FALLBACK",wholesaleEvidence:"Not approved for core Cuban BOTANICA sourcing.",culturalFit:"GENERIC"}
];

const resellers: Reseller[] = [
 {name:"Yoruba Distribuidores reseller network",market:"United States",model:"Registered botanicas + resellers",evidence:"Official site explicitly limits sales to registered botanicas, religious stores and resellers.",url:"https://yorubadistribuidores.com",fit:"High · Cuban/Santeria retail channel"},
 {name:"Babonsono retail partners",market:"United States",model:"B2B stores + resellers + retailers",evidence:"Official wholesale site states it supplies stores, resellers and retailers and requires business credentials.",url:"https://www.babonsono.com",fit:"High · broad botanica assortment"},
 {name:"BOTANICA independent online resellers",market:"USA + Abroad",model:"Independent ecommerce reseller",evidence:"Official wholesale policy explicitly welcomes independent online stores and international retailers; direct minimum $280.",url:"https://www.botanica.co/pages/wholesale",fit:"Medium · complementary branded goods"},
 {name:"Faire wholesale marketplace",market:"Worldwide",model:"Verified retailer marketplace",evidence:"Used as an official ordering channel by BOTANICA; retailer account gates wholesale access and pricing.",url:"https://www.faire.com",fit:"Medium · discovery/reseller channel"},
 {name:"Orisha Distributor retail network",market:"USA + Canada",model:"Botanicas · herb shops · naturist stores · health-food stores",evidence:"Official wholesale page identifies these retailer categories as existing clients and requires a seller permit for wholesale.",url:"https://www.orishadistributor.com/wholesale",fit:"High · specialist retail distribution"}
];

export default function OwnerSuppliersPage(){return <main className={styles.shell}><nav className={styles.nav}><a className={styles.brand} href="/owner"><span className={styles.mark}>O</span><span className={styles.brandText}><strong>BOTANICA</strong><small>OCHOSI</small></span></a><div className={styles.navLinks}><a className={styles.ghost} href="/owner">Owner OS</a><a className={styles.primary} href="/owner/catalog">Catalog Control</a></div></nav><div className={styles.content}>
<section className={styles.hero}><div className={styles.kicker}>SUPPLIER + RESELLER INTELLIGENCE · USA FIRST</div><h1>Supplier <em>Registry.</em></h1><p>Cuban BOTANICA sourcing prioritizes Miami, Hialeah and Houston, with a dedicated Nigeria/Yoruba sourcing lane for Ifa and practitioner-reviewed Lucumi-compatible goods. Nigerian Yoruba/Isese and Cuban Lucumi traditions are classified separately and are never assumed interchangeable.</p></section>
<div className={styles.statusStrip}><span className={styles.statusPill}>Miami / Hialeah · PRIORITY</span><span className={styles.statusPill}>Houston · PRIORITY</span><span className={styles.statusPill}>Nigeria / Yoruba · PROVENANCE GATE</span><span className={styles.statusPill}>Autonomous purchasing · LOCKED</span></div>
<section className={styles.section}><div className={styles.sectionHead}><div><span>Nigeria + Yoruba product lane</span><h2>Ifa and Orisha sourcing candidates.</h2></div></div><div className={styles.card}><p>Candidate assortment for commercial verification and practitioner review. Import legality, agricultural restrictions, provenance and cultural compatibility must pass before catalog activation.</p><div className={styles.productMeta}>{nigeriaProducts.map(item=><div key={item}>• {item}</div>)}</div></div></section>
<section className={styles.section}><div className={styles.sectionHead}><div><span>Verified sourcing evidence</span><h2>Cuban botanica wholesale candidates.</h2></div></div><div className={styles.actionGrid}>{suppliers.map(s=><div className={styles.card} key={s.name}><div className={styles.kicker}>PRIORITY {s.priority} · {s.status}</div><h2>{s.name}</h2><p><strong>{s.market}</strong> · {s.region}</p><p>{s.focus}</p><p>{s.channel}</p>{s.culturalFit&&<p><strong>Cultural fit:</strong> {s.culturalFit}</p>}<p><strong>Pricing evidence:</strong> {s.pricing}</p>{s.minimum&&<p><strong>Minimum:</strong> {s.minimum}</p>}<p>{s.wholesaleEvidence}</p>{!!s.priceExamples?.length&&<div className={styles.productMeta}>{s.priceExamples.map(item=><div key={item}>• {item}</div>)}</div>}<a className={styles.ghost} href={s.url} target="_blank" rel="noreferrer">Review verified website</a></div>)}</div></section>
<section className={styles.section}><div className={styles.sectionHead}><div><span>Distribution channels</span><h2>Verified reseller opportunities.</h2></div></div><div className={styles.actionGrid}>{resellers.map(r=><div className={styles.card} key={r.name}><div className={styles.kicker}>RESELLER CANDIDATE · PENDING REVIEW</div><h2>{r.name}</h2><p><strong>{r.market}</strong> · {r.model}</p><p><strong>BOTANICA fit:</strong> {r.fit}</p><p>{r.evidence}</p><a className={styles.ghost} href={r.url} target="_blank" rel="noreferrer">Review reseller channel</a></div>)}</div></section>
<section className={styles.section}><div className={styles.card}><div className={styles.kicker}>APPROVAL GATE</div><h2>Authenticity, legality and commercial approval are independent gates.</h2><p>Nigerian Ifa/Yoruba products require verified exporter identity, provenance, legal US import eligibility, current wholesale quote and practitioner compatibility review before they can be labeled for Cuban Santeria/Lucumi use. Fresh plant material, seeds, woods, animal-derived items and other regulated natural materials require additional import review and are not auto-approved. Supplier Agent recommendations cannot authorize spending.</p></div></section>
</div></main>}
