"use client";

import { useEffect, useMemo, useState } from "react";
import styles from "../owner.module.css";
import { BOTANICA_SUPPLIERS } from "@/lib/botanica-supplier-registry";

type SupplierProduct={id:string;supplier:string;sku:string;name:string;category:string;wholesalePrice:number;currency:string;moq:number;unit:string;productUrl:string;notes:string;updatedAt:string};
const STORAGE_KEY="botanica_owner_supplier_catalogs_v1";
const emptyProduct=():SupplierProduct=>({id:"",supplier:"",sku:"",name:"",category:"",wholesalePrice:0,currency:"USD",moq:1,unit:"unidad",productUrl:"",notes:"",updatedAt:""});
const normalize=(value:string)=>value.trim().toLocaleLowerCase("es").replace(/[^a-z0-9áéíóúüñ]+/g,"_");

function parseCsv(text:string){const rows:string[][]=[];let row:string[]=[],cell="",quoted=false;for(let i=0;i<text.length;i++){const char=text[i];if(char==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(char===","&&!quoted){row.push(cell);cell="";}else if((char==="\n"||char==="\r")&&!quoted){if(char==="\r"&&text[i+1]==="\n")i++;row.push(cell);if(row.some(v=>v.trim()))rows.push(row);row=[];cell="";}else cell+=char;}row.push(cell);if(row.some(v=>v.trim()))rows.push(row);return rows;}

export default function SupplierCatalogsPage(){
 const [products,setProducts]=useState<SupplierProduct[]>([]),[draft,setDraft]=useState<SupplierProduct>(emptyProduct()),[query,setQuery]=useState(""),[message,setMessage]=useState(""),[ready,setReady]=useState(false),[hasSession,setHasSession]=useState(false);
 useEffect(()=>{setHasSession(Boolean(localStorage.getItem("commerce_os_token")));try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY)??"[]") as SupplierProduct[];setProducts(Array.isArray(saved)?saved:[]);}catch{setProducts([]);}setReady(true);},[]);
 const persist=(next:SupplierProduct[])=>{setProducts(next);localStorage.setItem(STORAGE_KEY,JSON.stringify(next));};
 const visible=useMemo(()=>{const term=query.trim().toLocaleLowerCase("es");return products.filter(p=>!term||[p.supplier,p.sku,p.name,p.category,p.currency,p.notes].some(v=>String(v).toLocaleLowerCase("es").includes(term))).sort((a,b)=>a.supplier.localeCompare(b.supplier,"es")||a.name.localeCompare(b.name,"es"));},[products,query]);
 const save=(event:React.FormEvent)=>{event.preventDefault();if(!draft.supplier||!draft.name)return;const record={...draft,id:draft.id||crypto.randomUUID(),wholesalePrice:Number(draft.wholesalePrice)||0,moq:Math.max(1,Number(draft.moq)||1),updatedAt:new Date().toISOString()};persist(draft.id?products.map(p=>p.id===draft.id?record:p):[record,...products]);setDraft(emptyProduct());setMessage("Producto guardado en inteligencia interna.");};
 const importFile=async(file?:File)=>{if(!file)return;try{const text=await file.text();let records:Record<string,unknown>[]=[];if(file.name.toLowerCase().endsWith(".json")){const parsed=JSON.parse(text);if(!Array.isArray(parsed))throw new Error("El JSON debe contener una lista de productos.");records=parsed;}else{const rows=parseCsv(text);if(rows.length<2)throw new Error("El CSV necesita encabezados y al menos un producto.");const headers=rows[0].map(normalize);records=rows.slice(1).map(row=>Object.fromEntries(headers.map((header,index)=>[header,row[index]??""])));}
   const value=(record:Record<string,unknown>,...keys:string[])=>{for(const key of keys){const found=record[normalize(key)];if(found!==undefined&&found!==null&&String(found).trim())return String(found).trim();}return"";};
   const imported=records.map(record=>({id:crypto.randomUUID(),supplier:value(record,"supplier","proveedor","vendor"),sku:value(record,"sku","codigo","reference"),name:value(record,"name","product","producto","title"),category:value(record,"category","categoria","tipo"),wholesalePrice:Number(value(record,"wholesale_price","precio_mayorista","price","precio"))||0,currency:value(record,"currency","moneda")||"USD",moq:Math.max(1,Number(value(record,"moq","pedido_minimo","minimum_order"))||1),unit:value(record,"unit","unidad")||"unidad",productUrl:value(record,"product_url","url","website","enlace"),notes:value(record,"notes","notas","description","descripcion"),updatedAt:new Date().toISOString()})).filter(p=>p.supplier&&p.name);
   const keys=new Set(products.map(p=>`${normalize(p.supplier)}|${normalize(p.sku||p.name)}`));const unique=imported.filter(p=>{const key=`${normalize(p.supplier)}|${normalize(p.sku||p.name)}`;if(keys.has(key))return false;keys.add(key);return true;});persist([...products,...unique]);setMessage(`${unique.length} productos importados; ${imported.length-unique.length} duplicados omitidos.`);
  }catch(error){setMessage(error instanceof Error?error.message:"No se pudo importar el catálogo.");}};
 const download=(content:string,name:string,type:string)=>{const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement("a");a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);};
 const exportJson=()=>download(JSON.stringify(products,null,2),"catalogos-proveedores-botanica.json","application/json");
 const template="supplier,sku,name,category,wholesale_price,currency,moq,unit,product_url,notes\nEjemplo Proveedor,SKU-001,Vela blanca 7 días,Velas,1.25,USD,12,unidad,https://example.com/producto,Precio sujeto a confirmación\n";
 if(ready&&!hasSession)return <main className={styles.shell}><div className={styles.content}><div className={styles.error}><strong>Acceso privado requerido.</strong><p>Inicia sesión como propietario para administrar catálogos.</p><a className={styles.primary} href="/owner/login">Iniciar sesión</a></div></div></main>;
 return <main className={styles.shell}><nav className={styles.nav}><a className={styles.brand} href="/owner"><span className={styles.mark}>O</span><span className={styles.brandText}><strong>BOTANICA</strong><small>OCHOSI</small></span></a><div className={styles.navLinks}><a className={styles.ghost} href="/owner/directory">Mi directorio</a><a className={styles.primary} href="/owner">Owner OS</a></div></nav><div className={styles.content}>
  <section className={styles.hero}><div className={styles.kicker}>INTELIGENCIA COMERCIAL · CATÁLOGOS</div><h1>Productos y <em>precios.</em></h1><p>Incorpora catálogos de mayoristas mediante CSV o JSON, conserva el precio de origen y compáralos dentro del Owner OS. Importar no autoriza compras ni publicación en Shopify.</p><div className={styles.heroActions}><label className={styles.primary}>Importar CSV o JSON<input hidden type="file" accept=".csv,.json,text/csv,application/json" onChange={e=>void importFile(e.target.files?.[0])}/></label><button className={styles.ghost} onClick={()=>download(template,"plantilla-catalogo-proveedor.csv","text/csv")}>Descargar plantilla CSV</button><button className={styles.ghost} disabled={!products.length} onClick={exportJson}>Exportar respaldo</button></div></section>
  <div className={styles.statusStrip}><span className={styles.statusPill}>{products.length} productos</span><span className={styles.statusPill}>{new Set(products.map(p=>p.supplier)).size} proveedores</span><span className={styles.statusPill}>Shopify · publicación bloqueada</span></div>{message&&<div className={styles.result}>{message}</div>}
  <section className={styles.section}><div className={styles.card}><div className={styles.kicker}>{draft.id?"EDITAR PRODUCTO":"ENTRADA MANUAL"}</div><h2>{draft.id?"Actualizar producto":"Añadir producto mayorista"}</h2><form className={styles.form} onSubmit={save}><select required className={styles.input} aria-label="Proveedor" value={draft.supplier} onChange={e=>setDraft({...draft,supplier:e.target.value})}><option value="">Seleccionar proveedor</option>{BOTANICA_SUPPLIERS.map(s=><option key={s.id}>{s.name}</option>)}</select><input className={styles.input} placeholder="SKU o referencia" value={draft.sku} onChange={e=>setDraft({...draft,sku:e.target.value})}/><input required className={styles.input} placeholder="Nombre del producto" value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/><input className={styles.input} placeholder="Categoría" value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})}/><input className={styles.input} type="number" min="0" step="0.01" placeholder="Precio mayorista" value={draft.wholesalePrice||""} onChange={e=>setDraft({...draft,wholesalePrice:Number(e.target.value)})}/><select className={styles.input} value={draft.currency} onChange={e=>setDraft({...draft,currency:e.target.value})}><option>USD</option><option>NGN</option><option>INR</option><option>CNY</option><option>EUR</option><option>GBP</option></select><input className={styles.input} type="number" min="1" placeholder="MOQ" value={draft.moq} onChange={e=>setDraft({...draft,moq:Number(e.target.value)})}/><input className={styles.input} placeholder="Unidad: pieza, caja…" value={draft.unit} onChange={e=>setDraft({...draft,unit:e.target.value})}/><input className={styles.input} placeholder="URL del producto" value={draft.productUrl} onChange={e=>setDraft({...draft,productUrl:e.target.value})}/><textarea className={`${styles.textarea} ${styles.full}`} placeholder="Notas, vigencia, materiales o condiciones" value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})}/><div className={`${styles.rowActions} ${styles.full}`}><button className={styles.primary} type="submit">{draft.id?"Guardar cambios":"Añadir producto"}</button>{draft.id&&<button type="button" className={styles.ghost} onClick={()=>setDraft(emptyProduct())}>Cancelar</button>}</div></form></div></section>
  <section className={styles.section}><div className={styles.sectionHead}><div><span>CATÁLOGOS IMPORTADOS</span><h2>Comparador interno.</h2></div><input className={styles.input} style={{maxWidth:360}} placeholder="Buscar proveedor, SKU o producto…" value={query} onChange={e=>setQuery(e.target.value)}/></div>{!visible.length?<div className={styles.empty}>Todavía no hay productos. Descarga la plantilla o añade uno manualmente.</div>:<div className={styles.productList}>{visible.map(p=><article className={`${styles.card} ${styles.productRow}`} key={p.id}><div><div className={styles.kicker}>{p.supplier} · {p.sku||"SIN SKU"}</div><h2>{p.name}</h2><div className={styles.metricValue}>{new Intl.NumberFormat("es-US",{style:"currency",currency:p.currency||"USD"}).format(p.wholesalePrice)}</div><div className={styles.productMeta}>{p.category||"Sin categoría"} · MOQ {p.moq} {p.unit}{p.notes?` · ${p.notes}`:""}</div>{p.productUrl&&<a href={p.productUrl} target="_blank" rel="noreferrer">Abrir producto ↗</a>}</div><div className={styles.rowActions}><button className={styles.ghost} onClick={()=>{setDraft(p);window.scrollTo({top:0,behavior:"smooth"});}}>Editar</button><button className={styles.danger} onClick={()=>{if(confirm("¿Eliminar este producto del catálogo interno?"))persist(products.filter(item=>item.id!==p.id));}}>Eliminar</button></div></article>)}</div>}</section>
 </div></main>;
}
