"use client";

import { useEffect, useState } from "react";
import styles from "../owner.module.css";

type Brief = { workspace_url:string; query:string; prompt:string; required_evidence:string[]; prohibited_actions:string[]; completion_rule:string };

export default function AccioWorkPage() {
  const [token,setToken]=useState(""),[orgId,setOrgId]=useState(""),[ready,setReady]=useState(false);
  const [query,setQuery]=useState("Lucumi and Orisha devotional supplies wholesale"),[destination,setDestination]=useState("United States");
  const [targetRetailUsd,setTargetRetailUsd]=useState(36),[maximumMoq,setMaximumMoq]=useState(6);
  const [brief,setBrief]=useState<Brief|null>(null),[message,setMessage]=useState(""),[working,setWorking]=useState(false);
  useEffect(()=>{setToken(localStorage.getItem("commerce_os_token")??"");setOrgId(localStorage.getItem("commerce_os_org")??"");setReady(true);},[]);
  const prepare=async()=>{setWorking(true);setMessage("");setBrief(null);try{const response=await fetch(`/api/orgs/${orgId}/accio/brief`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({query,destination,targetRetailUsd,maximumMoq})});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.detail??"No se pudo preparar el trabajo de Accio.");setBrief(result.brief);setMessage("Trabajo preparado. Copia el brief, ejecútalo en Accio Work y devuelve la evidencia al Owner OS.");}catch(cause){setMessage(cause instanceof Error?cause.message:"No se pudo preparar el trabajo de Accio.");}finally{setWorking(false);}};
  const copyPrompt=async()=>{if(!brief)return;await navigator.clipboard.writeText(brief.prompt);setMessage("Brief copiado. Accio sigue en modo investigación; no autoriza contacto, compra ni publicación.");};
  if(!ready)return <main className={styles.shell}><div className={styles.content}><div className={styles.result}>Verificando acceso Owner…</div></div></main>;
  if(!token||!orgId)return <main className={styles.shell}><div className={styles.content}><div className={styles.error}><strong>Acceso privado requerido.</strong><p>Inicia sesión como propietario para preparar trabajos de sourcing.</p><a className={styles.primary} href="/owner/login">Iniciar sesión</a></div></div></main>;
  return <main className={styles.shell}><nav className={styles.nav}><a className={styles.brand} href="/owner"><span className={styles.mark}>O</span><span className={styles.brandText}><strong>BOTANICA</strong><small>OCHOSI</small></span></a><div className={styles.navLinks}><a className={styles.ghost} href="/owner/suppliers">Proveedores</a><a className={styles.primary} href="/owner">Owner OS</a></div></nav><div className={styles.content}>
    <section className={styles.hero}><div className={styles.kicker}>ACCIO WORK · SOURCING CONTROLADO</div><h1>Investigar, <em>no comprar.</em></h1><p>Accio busca y compara evidencia de proveedores para surtido Botanica/Lucumi/Orisha. Todos los candidatos quedan en HOLD hasta revisión del propietario y Council.</p></section>
    <section className={styles.section}><div className={styles.card}><div className={styles.form}><label className={styles.full}>Necesidad de sourcing<input className={styles.input} value={query} maxLength={500} onChange={event=>setQuery(event.target.value)} placeholder="Ej. velas devocionales Orisha al por mayor"/></label><label>Destino<input className={styles.input} value={destination} maxLength={200} onChange={event=>setDestination(event.target.value)}/></label><label>Retail objetivo USD<input className={styles.input} type="number" min="0" step="0.01" value={targetRetailUsd||""} onChange={event=>setTargetRetailUsd(Number(event.target.value))}/></label><label>MOQ máximo<input className={styles.input} type="number" min="1" step="1" value={maximumMoq} onChange={event=>setMaximumMoq(Number(event.target.value))}/></label><div className={`${styles.heroActions} ${styles.full}`}><button className={styles.primary} disabled={working||!query.trim()} onClick={()=>void prepare()}>{working?"Preparando…":"Preparar trabajo correcto"}</button></div></div>{message&&<div className={brief?styles.result:styles.error}>{message}</div>}</div></section>
    {brief&&<section className={styles.section}><div className={styles.split}><article className={styles.card}><div className={styles.kicker}>BRIEF LISTO PARA ACCIO</div><h2>{brief.query}</h2><textarea className={`${styles.textarea} ${styles.full}`} style={{minHeight:360}} readOnly value={brief.prompt}/><div className={styles.heroActions}><button className={styles.primary} onClick={()=>void copyPrompt()}>Copiar brief</button><a className={styles.ghost} href={brief.workspace_url} target="_blank" rel="noreferrer">Abrir Accio Work ↗</a></div></article><article className={styles.card}><div className={styles.kicker}>GOVERNANCE</div><h2>Trabajo permitido</h2><p>{brief.completion_rule}</p>{brief.required_evidence.map(item=><div className={styles.check} key={item}><small>✓ {item}</small></div>)}<h2 style={{marginTop:24}}>Acciones prohibidas</h2>{brief.prohibited_actions.map(item=><div className={styles.check} key={item}><small className={styles.warning}>LOCKED · {item}</small></div>)}</article></div></section>}
  </div></main>;
}
