/**
 * Accio Work sourcing intake.
 *
 * Accio Work (Alibaba International) is a desktop agent the owner runs by hand:
 * it discovers Alibaba.com suppliers, sends inquiries and consolidates quotes.
 * It exposes no server API, so nothing here ever calls it — this module takes
 * the quote the owner brings back and decides what it means for this business.
 *
 * Two facts drive every rule below:
 *
 *  1. Accio output is a supplier *claim* generated by an AI agent, not a
 *     verified fact. Nothing is eligible until the owner attests they checked
 *     it against the supplier profile themselves.
 *  2. Alibaba.com is MOQ wholesale, and the order-funded gate in
 *     `zero-capital-launch.ts` refuses MOQ > 1 by construction. So a quote that
 *     needs inventory is routed as INVENTORY_REQUIRED with the capital named,
 *     rather than silently failing as if it were a bad deal.
 *
 * Advisory only: never publishes, never spends, never contacts a supplier.
 */
import { calculateSupplierDealIntelligence } from "./supplier-deal-intelligence";
import { assessZeroCapitalCandidate, ZERO_CAPITAL_DEFAULTS, type ZeroCapitalCandidate } from "./zero-capital-launch";

/** How a quote can be acted on, if at all. */
export type AccioRoute = "ORDER_FUNDED" | "INVENTORY_REQUIRED" | "REJECTED";

export type AccioCandidate = ZeroCapitalCandidate & {
  quoteReference?: string;
  supplierName?: string;
  supplierProfileUrl?: string;
  /** The owner confirms they opened the supplier profile and checked the quote. */
  ownerVerifiedQuote?: boolean;
  sampleOrderAvailable?: boolean;
  samplePriceUsd?: number;
};

const money = (value: number) => Math.round(value * 100) / 100;
const filled = (value: unknown) => String(value ?? "").trim().length > 0;

export function assessAccioCandidate(input: AccioCandidate) {
  const deal = calculateSupplierDealIntelligence(input);
  const zeroCapital = assessZeroCapitalCandidate(input);

  // Problems that are wrong with the *quote itself*, independent of capital.
  const disqualifiers: string[] = [];
  if (!input.ownerVerifiedQuote) disqualifiers.push("La cotización de Accio no ha sido verificada por el propietario contra el perfil del proveedor.");
  if (!filled(input.supplierName) || !filled(input.supplierProfileUrl)) disqualifiers.push("Falta el nombre o el enlace del perfil del proveedor de Alibaba.");
  if (!deal.fxReady || deal.landedUnitCostUsd <= 0) disqualifiers.push("Costo puesto en almacén o conversión USD sin verificar.");
  if (input.inventoryStatus !== "IN_STOCK" || !filled(input.inventoryVerifiedAt)) disqualifiers.push("Inventario actual sin verificación fechada.");
  if (input.resaleAuthorizationStatus !== "VERIFIED" || !filled(input.authorizationReference)) disqualifiers.push("Autorización de reventa sin evidencia verificada.");
  if (deal.totalDays <= 0 || deal.totalDays > ZERO_CAPITAL_DEFAULTS.maximumDeliveryDays) disqualifiers.push(`El plazo total no está confirmado dentro de ${ZERO_CAPITAL_DEFAULTS.maximumDeliveryDays} días.`);
  if (deal.retailProfitPerUnitUsd <= 0) disqualifiers.push("El precio de venta no cubre el costo puesto en almacén.");

  // Needing money up front does not kill a quote — it changes which route it
  // belongs to. Capital comes back as *revenue*, not as profit, so break-even
  // is the outlay divided by the retail price: sell that many units of the
  // batch and the money is home; the rest of the batch is the upside.
  const capitalRequiredUsd = deal.supplierMinimumInvestmentUsd;
  const needsCapital = deal.supplierOrderQuantity !== 1 || capitalRequiredUsd > ZERO_CAPITAL_DEFAULTS.maximumSupplierCommitmentUsd;
  const unitsToRecoverCapital = deal.retailPriceUsd > 0 ? Math.ceil(capitalRequiredUsd / deal.retailPriceUsd) : 0;
  /** Share of the batch that must sell just to get the money back. */
  const breakEvenSellThroughPercent = deal.supplierOrderQuantity > 0 ? money(unitsToRecoverCapital / deal.supplierOrderQuantity * 100) : 0;

  const route: AccioRoute = disqualifiers.length > 0 ? "REJECTED" : !needsCapital && zeroCapital.eligible ? "ORDER_FUNDED" : "INVENTORY_REQUIRED";

  const actions: string[] = [];
  if (route === "ORDER_FUNDED") actions.push("Puede operarse con el modelo financiado por pedido: cobrar primero, comprar después.");
  if (route === "INVENTORY_REQUIRED") {
    actions.push(`Requiere $${capitalRequiredUsd.toFixed(2)} de capital propio antes de la primera venta; el modelo financiado por pedido no aplica.`);
    actions.push(`Recuperas el capital al vender ${unitsToRecoverCapital} de ${deal.supplierOrderQuantity} unidades del lote (${breakEvenSellThroughPercent.toFixed(1)}%).`);
    if (breakEvenSellThroughPercent > 70) actions.push("Margen de seguridad estrecho: casi todo el lote debe venderse solo para recuperar la inversión. Renegocia el precio o reduce el MOQ.");
    if (input.sampleOrderAvailable) actions.push(`Pide primero la muestra${input.samplePriceUsd ? ` ($${money(input.samplePriceUsd).toFixed(2)})` : ""} y verifica calidad antes de comprometer el lote.`);
    else actions.push("El proveedor no ofrece muestra: exige una antes de comprometer capital.");
  }
  if (route === "REJECTED") actions.push("No comprometas dinero con esta cotización hasta resolver los puntos anteriores.");

  return {
    route,
    quoteReference: String(input.quoteReference ?? "").trim(),
    supplierName: String(input.supplierName ?? "").trim(),
    supplierProfileUrl: String(input.supplierProfileUrl ?? "").trim(),
    eligibleForOrderFunding: route === "ORDER_FUNDED",
    disqualifiers,
    actions,
    capitalRequiredUsd,
    unitsToRecoverCapital,
    breakEvenSellThroughPercent,
    moq: deal.supplierOrderQuantity,
    landedUnitCostUsd: deal.landedUnitCostUsd,
    retailPriceUsd: deal.retailPriceUsd,
    retailProfitPerUnitUsd: deal.retailProfitPerUnitUsd,
    retailMarginPercent: deal.retailMarginPercent,
    retailProfitPerSupplierOrderUsd: deal.retailProfitPerSupplierOrderUsd,
    totalDays: deal.totalDays,
    zeroCapital,
  };
}

export type AccioAssessment = ReturnType<typeof assessAccioCandidate>;

const routeRank: Record<AccioRoute, number> = { ORDER_FUNDED: 0, INVENTORY_REQUIRED: 1, REJECTED: 2 };

/**
 * Rank a batch of Accio quotes: what can be sold without capital first, then
 * what needs the least capital per dollar of batch profit, then the rejects.
 */
export function assessAccioSourcingBatch(candidates: AccioCandidate[]) {
  const results = (candidates ?? []).map(assessAccioCandidate);
  const ranked = [...results].sort((a, b) => {
    if (routeRank[a.route] !== routeRank[b.route]) return routeRank[a.route] - routeRank[b.route];
    if (a.route === "ORDER_FUNDED") return b.retailProfitPerUnitUsd - a.retailProfitPerUnitUsd;
    if (a.route === "INVENTORY_REQUIRED") return a.capitalRequiredUsd - b.capitalRequiredUsd;
    return a.disqualifiers.length - b.disqualifiers.length;
  });
  return {
    assessed: results.length,
    orderFunded: results.filter((r) => r.route === "ORDER_FUNDED").length,
    inventoryRequired: results.filter((r) => r.route === "INVENTORY_REQUIRED").length,
    rejected: results.filter((r) => r.route === "REJECTED").length,
    capitalToTakeEveryInventoryDealUsd: money(results.filter((r) => r.route === "INVENTORY_REQUIRED").reduce((total, r) => total + r.capitalRequiredUsd, 0)),
    results: ranked,
  };
}

export const ACCIO_OWNER_RULES = [
  "Accio propone y negocia; no verifica. Confirma cada dato en el perfil del proveedor antes de aceptarlo.",
  "Ninguna cotización entra al catálogo sin inventario verificado y autorización de reventa documentada.",
  "Alibaba opera con MOQ: una cotización con MOQ mayor a 1 exige capital propio y sale del modelo financiado por pedido.",
  "Pide muestra y verifica calidad antes de comprometer el capital de un lote completo.",
  "No permitas que el agente cierre pagos: la orden al proveedor se aprueba manualmente en Owner OS.",
  "Guarda la referencia de cotización y el enlace del proveedor con cada decisión para poder auditarla.",
] as const;
