export type BotanicaSkuLane =
  | "NIGERIA_YORUBA"
  | "CUBAN_LUCUMI"
  | "BOTANICA_CONSUMABLES";

export type BotanicaSkuEvidenceStatus =
  | "PUBLIC_PRODUCT"
  | "WHOLESALE_PRODUCT"
  | "WHOLESALE_CATEGORY"
  | "WHOLESALE_LOGIN_REQUIRED";

export interface BotanicaSkuCandidate {
  sku: string;
  title: string;
  lane: BotanicaSkuLane;
  supplier: string;
  sourceUrl: string;
  evidenceStatus: BotanicaSkuEvidenceStatus;
  observedRetailPriceUsd?: number;
  wholesaleCostUsd?: number;
  inventoryVerified: boolean;
  landedCostVerified: boolean;
  publishStatus: "HOLD";
  notes: string;
}

/**
 * First commercial candidate basket for BOTANICA OCHOSI.
 *
 * These are real, source-backed products/categories, but none are publish-ready solely
 * because they appear in this list. Wholesale cost, stock, landed cost, cultural/provenance
 * checks, margin, images, and Council approval must still pass before Shopify activation.
 */
export const BOTANICA_FIRST_25_SKU_CANDIDATES: BotanicaSkuCandidate[] = [
  {
    sku: "BO-NG-OPON-IFE-LG",
    title: "Opon Ifá — Ife Design — Large",
    lane: "NIGERIA_YORUBA",
    supplier: "Yoruba Imports",
    sourceUrl: "https://yorubaimports.com/",
    evidenceStatus: "PUBLIC_PRODUCT",
    observedRetailPriceUsd: 150,
    inventoryVerified: false,
    landedCostVerified: false,
    publishStatus: "HOLD",
    notes: "Public product/price observed; obtain wholesale quote and stock confirmation before Council.",
  },
  {
    sku: "BO-NG-OPON-ASSORTED",
    title: "Opon Ifá — Ife Designs Assorted",
    lane: "NIGERIA_YORUBA",
    supplier: "Yoruba Imports",
    sourceUrl: "https://yorubaimports.com/",
    evidenceStatus: "PUBLIC_PRODUCT",
    observedRetailPriceUsd: 100,
    inventoryVerified: false,
    landedCostVerified: false,
    publishStatus: "HOLD",
    notes: "Public product/price observed; wholesale economics still required.",
  },
  {
    sku: "BO-NG-EDUN-ARA",
    title: "Edun Ara — Sango Thunder Stone",
    lane: "NIGERIA_YORUBA",
    supplier: "Yoruba Imports",
    sourceUrl: "https://yorubaimports.com/",
    evidenceStatus: "PUBLIC_PRODUCT",
    observedRetailPriceUsd: 7,
    inventoryVerified: false,
    landedCostVerified: false,
    publishStatus: "HOLD",
    notes: "Public benchmark only; provenance/cultural review required before listing language is approved.",
  },
  {
    sku: "BO-NG-ESU-AJE",
    title: "Esu Aje",
    lane: "NIGERIA_YORUBA",
    supplier: "Yoruba Imports",
    sourceUrl: "https://yorubaimports.com/",
    evidenceStatus: "PUBLIC_PRODUCT",
    observedRetailPriceUsd: 100,
    inventoryVerified: false,
    landedCostVerified: false,
    publishStatus: "HOLD",
    notes: "Public product/price observed; require wholesale cost and provenance evidence.",
  },
  {
    sku: "BO-NG-IYEROSUN",
    title: "Iyeri Osun / Iyerosun",
    lane: "NIGERIA_YORUBA",
    supplier: "Yoruba Imports",
    sourceUrl: "https://yorubaimports.com/",
    evidenceStatus: "PUBLIC_PRODUCT",
    observedRetailPriceUsd: 25,
    inventoryVerified: false,
    landedCostVerified: false,
    publishStatus: "HOLD",
    notes: "Public benchmark only; wholesale and stock confirmation required.",
  },
  {
    sku: "BO-NG-OROGBO",
    title: "Orogbo — Bitter Kola",
    lane: "NIGERIA_YORUBA",
    supplier: "Yoruba Imports",
    sourceUrl: "https://yorubaimports.com/",
    evidenceStatus: "PUBLIC_PRODUCT",
    observedRetailPriceUsd: 10,
    inventoryVerified: false,
    landedCostVerified: false,
    publishStatus: "HOLD",
    notes: "Perishable/agricultural handling and import rules must be verified before sale.",
  },
  {
    sku: "BO-NG-OBI-ABATA",
    title: "Obi Abata — Fresh Kola Nuts",
    lane: "NIGERIA_YORUBA",
    supplier: "Yoruba Imports",
    sourceUrl: "https://yorubaimports.com/",
    evidenceStatus: "PUBLIC_PRODUCT",
    observedRetailPriceUsd: 30,
    inventoryVerified: false,
    landedCostVerified: false,
    publishStatus: "HOLD",
    notes: "Fresh product; verify shelf life, stock, shipping and any agricultural restrictions.",
  },
  {
    sku: "BO-NG-EWE-HERBS",
    title: "Ewe — West African Herbs",
    lane: "NIGERIA_YORUBA",
    supplier: "Yoruba Imports",
    sourceUrl: "https://yorubaimports.com/",
    evidenceStatus: "PUBLIC_PRODUCT",
    inventoryVerified: false,
    landedCostVerified: false,
    publishStatus: "HOLD",
    notes: "Do not publish medical claims; identify exact species/product before listing.",
  },
  {
    sku: "BO-NG-OPON-WHOLESALE",
    title: "Pilón / Tablero Opon Ifá",
    lane: "NIGERIA_YORUBA",
    supplier: "Yoruba Distribuidores LLC",
    sourceUrl: "https://yorubadistribuidores.com/product/pilon-tablero-opon-ifa/",
    evidenceStatus: "WHOLESALE_PRODUCT",
    inventoryVerified: false,
    landedCostVerified: false,
    publishStatus: "HOLD",
    notes: "Explicit wholesale product; request exact cost, MOQ, materials and lead time.",
  },
  {
    sku: "BO-LC-COLLAR-YEMAYA",
    title: "Collar Yemayá Azul y Blanco con Ildé",
    lane: "CUBAN_LUCUMI",
    supplier: "Yoruba Distribuidores LLC",
    sourceUrl: "https://yorubadistribuidores.com/product/collar-yemaya-azul-blanco/",
    evidenceStatus: "WHOLESALE_PRODUCT",
    inventoryVerified: false,
    landedCostVerified: false,
    publishStatus: "HOLD",
    notes: "Wholesale product; cultural preparation/consecration claims must be independently verified before repeating them.",
  },
  {
    sku: "BO-LC-ILDE-OYA",
    title: "Ildé Oyá Elástico Grueso",
    lane: "CUBAN_LUCUMI",
    supplier: "Yoruba Distribuidores LLC",
    sourceUrl: "https://yorubadistribuidores.com/product/ilde-oya-elastico-grueso/",
    evidenceStatus: "WHOLESALE_PRODUCT",
    inventoryVerified: false,
    landedCostVerified: false,
    publishStatus: "HOLD",
    notes: "Wholesale product; verify material, unit/case quantity and any ritual-preparation claims separately.",
  },
  {
    sku: "BO-LC-COLLARES-ORISHA",
    title: "Collares Orisha — Assorted",
    lane: "CUBAN_LUCUMI",
    supplier: "Yoruba Distribuidores LLC",
    sourceUrl: "https://yorubadistribuidores.com/",
    evidenceStatus: "WHOLESALE_CATEGORY",
    inventoryVerified: false,
    landedCostVerified: false,
    publishStatus: "HOLD",
    notes: "Break into specific Orisha/color variants only after wholesale catalog data is obtained.",
  },
  {
    sku: "BO-LC-HERRAMIENTAS-ORISHA",
    title: "Herramientas Orisha — Assorted",
    lane: "CUBAN_LUCUMI",
    supplier: "Yoruba Distribuidores LLC",
    sourceUrl: "https://yorubadistribuidores.com/",
    evidenceStatus: "WHOLESALE_CATEGORY",
    inventoryVerified: false,
    landedCostVerified: false,
    publishStatus: "HOLD",
    notes: "Require exact itemization, materials, origin and tradition mapping before variants are created.",
  },
  {
    sku: "BO-LC-ABANICOS-YORUBA",
    title: "Abanicos Yoruba — Assorted",
    lane: "CUBAN_LUCUMI",
    supplier: "Yoruba Distribuidores LLC",
    sourceUrl: "https://yorubadistribuidores.com/",
    evidenceStatus: "WHOLESALE_CATEGORY",
    inventoryVerified: false,
    landedCostVerified: false,
    publishStatus: "HOLD",
    notes: "Wholesale category; exact SKU and cost required.",
  },
  {
    sku: "BO-LC-SOPERA-OSHUN",
    title: "Sopera de Porcelana Fina Oshún",
    lane: "CUBAN_LUCUMI",
    supplier: "Religion Universe",
    sourceUrl: "https://religionuniverse.com/",
    evidenceStatus: "WHOLESALE_LOGIN_REQUIRED",
    inventoryVerified: false,
    landedCostVerified: false,
    publishStatus: "HOLD",
    notes: "Product publicly visible; wholesale price requires approved account/login.",
  },
  {
    sku: "BO-LC-SOPERA-YEMAYA",
    title: "Sopera de Porcelana Fina Yemayá",
    lane: "CUBAN_LUCUMI",
    supplier: "Religion Universe",
    sourceUrl: "https://religionuniverse.com/",
    evidenceStatus: "WHOLESALE_LOGIN_REQUIRED",
    inventoryVerified: false,
    landedCostVerified: false,
    publishStatus: "HOLD",
    notes: "Product publicly visible; wholesale price requires approved account/login.",
  },
  {
    sku: "BO-LC-CORONAS",
    title: "Coronas Religiosas — Assorted",
    lane: "CUBAN_LUCUMI",
    supplier: "Religion Universe",
    sourceUrl: "https://religionuniverse.com/",
    evidenceStatus: "WHOLESALE_LOGIN_REQUIRED",
    inventoryVerified: false,
    landedCostVerified: false,
    publishStatus: "HOLD",
    notes: "Wholesale category visible; exact variants and pricing require login.",
  },
  {
    sku: "BO-LC-MARACAS",
    title: "Maracas Religiosas — Assorted",
    lane: "CUBAN_LUCUMI",
    supplier: "Religion Universe",
    sourceUrl: "https://religionuniverse.com/",
    evidenceStatus: "WHOLESALE_LOGIN_REQUIRED",
    inventoryVerified: false,
    landedCostVerified: false,
    publishStatus: "HOLD",
    notes: "Wholesale category visible; exact product data required before listing.",
  },
  {
    sku: "BO-BC-VELAS-7D",
    title: "Veladoras Religiosas de 7 Días — Assorted",
    lane: "BOTANICA_CONSUMABLES",
    supplier: "Distribuidora Más Allá",
    sourceUrl: "https://www.el-masalla.com/productos/",
    evidenceStatus: "WHOLESALE_CATEGORY",
    inventoryVerified: false,
    landedCostVerified: false,
    publishStatus: "HOLD",
    notes: "Wholesale category; create individual variants only from current catalog/price list.",
  },
  {
    sku: "BO-BC-ACEITES",
    title: "Aceites Espirituales — Assorted",
    lane: "BOTANICA_CONSUMABLES",
    supplier: "Distribuidora Más Allá",
    sourceUrl: "https://www.el-masalla.com/productos/",
    evidenceStatus: "WHOLESALE_CATEGORY",
    inventoryVerified: false,
    landedCostVerified: false,
    publishStatus: "HOLD",
    notes: "No health/guarantee claims; exact fragrance/formula SKU and wholesale cost required.",
  },
  {
    sku: "BO-BC-BANOS",
    title: "Baños Espirituales — Assorted",
    lane: "BOTANICA_CONSUMABLES",
    supplier: "Distribuidora Más Allá",
    sourceUrl: "https://www.el-masalla.com/wholesale-customers/wholesale-catalog/",
    evidenceStatus: "WHOLESALE_CATEGORY",
    inventoryVerified: false,
    landedCostVerified: false,
    publishStatus: "HOLD",
    notes: "Exact SKU/ingredients/cost required; no therapeutic claims.",
  },
  {
    sku: "BO-BC-JABONES",
    title: "Jabones Esotéricos — Assorted",
    lane: "BOTANICA_CONSUMABLES",
    supplier: "Distribuidora Más Allá",
    sourceUrl: "https://www.el-masalla.com/wholesale-customers/wholesale-catalog/",
    evidenceStatus: "WHOLESALE_CATEGORY",
    inventoryVerified: false,
    landedCostVerified: false,
    publishStatus: "HOLD",
    notes: "Exact SKU/ingredients/cost required; no medical claims.",
  },
  {
    sku: "BO-BC-INCIENSOS",
    title: "Inciensos — Assorted",
    lane: "BOTANICA_CONSUMABLES",
    supplier: "Distribuidora Más Allá",
    sourceUrl: "https://www.el-masalla.com/wholesale-customers/wholesale-catalog/",
    evidenceStatus: "WHOLESALE_CATEGORY",
    inventoryVerified: false,
    landedCostVerified: false,
    publishStatus: "HOLD",
    notes: "Exact scent/brand/unit count and cost required before activation.",
  },
  {
    sku: "BO-BC-COLONIAS",
    title: "Colonias Místicas — Assorted",
    lane: "BOTANICA_CONSUMABLES",
    supplier: "Distribuidora Más Allá",
    sourceUrl: "https://www.el-masalla.com/wholesale-customers/wholesale-catalog/",
    evidenceStatus: "WHOLESALE_CATEGORY",
    inventoryVerified: false,
    landedCostVerified: false,
    publishStatus: "HOLD",
    notes: "Exact bottle size, ingredients/labeling and wholesale cost required.",
  },
  {
    sku: "BO-BC-ESENCIAS",
    title: "Esencias Místicas — Assorted",
    lane: "BOTANICA_CONSUMABLES",
    supplier: "Distribuidora Más Allá",
    sourceUrl: "https://www.el-masalla.com/wholesale-customers/wholesale-catalog/",
    evidenceStatus: "WHOLESALE_CATEGORY",
    inventoryVerified: false,
    landedCostVerified: false,
    publishStatus: "HOLD",
    notes: "Exact SKU, packaging, compliance and wholesale cost required.",
  },
];

export function getBotanicaFirst25SkuCandidates() {
  return BOTANICA_FIRST_25_SKU_CANDIDATES.map((candidate) => ({ ...candidate }));
}
