export type IfaLiteratureResearchRecord = {
  id:string; title:string; author:string; isbn:string; publisher:string; publicationCountry:string;
  languages:string[]; bookCollection:"IFA"|"ODU_PATAKINES"|"YORUBA"|"HISTORIA_ESTUDIOS"; sourceUrl:string; sourceLabel:string;
};

/** Bibliographic leads only. Commercial availability, reseller rights and wholesale terms remain unverified. */
export const IFA_LITERATURE_RESEARCH:IfaLiteratureResearchRecord[]=[
 {id:"ifa-exposition-abimbola",title:"Ifá: An Exposition of Ifá Literary Corpus",author:"Wándé Abímbọ́lá",isbn:"9780195751994",publisher:"Oxford University Press Nigeria",publicationCountry:"Nigeria",languages:["en"],bookCollection:"IFA",sourceUrl:"https://books.google.com/books/about/If%C3%A1.html?id=SI4IAQAAIAAJ",sourceLabel:"Google Books bibliographic record"},
 {id:"ifa-divination-poetry",title:"Ifá Divination Poetry",author:"Wándé Abímbọ́lá",isbn:"9780883570470",publisher:"NOK Publishers",publicationCountry:"United States",languages:["yo","en"],bookCollection:"ODU_PATAKINES",sourceUrl:"https://books.google.com/books/about/If%C3%A1_Divination_Poetry.html?id=RF9-AAAAMAAJ",sourceLabel:"Google Books bibliographic record"},
 {id:"sixteen-great-poems",title:"Sixteen Great Poems of Ifá",author:"Wándé Abímbọ́lá",isbn:"",publisher:"University Press PLC / earlier UNESCO edition",publicationCountry:"Nigeria",languages:["yo","en"],bookCollection:"ODU_PATAKINES",sourceUrl:"https://universitypressplc.com/product/sixteen-great-poems-of-ifa/",sourceLabel:"Publisher product page"},
 {id:"ifa-divination-bascom",title:"Ifa Divination: Communication Between Gods and Men in West Africa",author:"William W. Bascom",isbn:"9780253206381",publisher:"Indiana University Press",publicationCountry:"United States",languages:["en"],bookCollection:"IFA",sourceUrl:"https://iupress.org/9780253114655/ifa-divination/",sourceLabel:"Publisher product page"},
 {id:"ifa-knowledge-power-performance",title:"Ifá Divination, Knowledge, Power, and Performance",author:"Jacob K. Olupona and Rowland O. Abiodun, editors",isbn:"9780253018823",publisher:"Indiana University Press",publicationCountry:"United States",languages:["en"],bookCollection:"HISTORIA_ESTUDIOS",sourceUrl:"https://books.google.com/books/about/If%C3%A1_Divination_Knowledge_Power_and_Perf.html?id=491YrgEACAAJ",sourceLabel:"Google Books bibliographic record"},
 {id:"ifa-will-mend",title:"Ifá Will Mend Our Broken World",author:"Wándé Abímbọ́lá with Ivor Miller",isbn:"9780965973908",publisher:"Iroko Academic Publishers",publicationCountry:"United States",languages:["en"],bookCollection:"HISTORIA_ESTUDIOS",sourceUrl:"https://books.google.com/books/about/If%C3%A1_Will_Mend_Our_Broken_World.html?id=LEbVojp2l-IC",sourceLabel:"Google Books bibliographic record"},
 {id:"ifa-god-divination",title:"Ifa: The Yoruba God of Divination in Nigeria and the United States",author:"Louis Djisovi Ikukomi Eason",isbn:"9781592216406",publisher:"Africa World Press",publicationCountry:"United States",languages:["en"],bookCollection:"HISTORIA_ESTUDIOS",sourceUrl:"https://books.google.com/books/about/Ifa.html?id=whsRAQAAIAAJ",sourceLabel:"Google Books bibliographic record"},
 {id:"ifa-practice-ajayi",title:"Ifa Divination: Its Practice Among the Yoruba of Nigeria",author:"Bádé Àjàyí",isbn:"9789782066312",publisher:"Unilorin Press",publicationCountry:"Nigeria",languages:["en"],bookCollection:"IFA",sourceUrl:"https://books.google.com/books/about/Ifa_Divination.html?id=KckQAQAAIAAJ",sourceLabel:"Google Books bibliographic record"},
 {id:"poesia-divinatoria",title:"Poesia divinatória de Ifá",author:"Wándé Abímbọ́lá",isbn:"9798468453568",publisher:"Publisher verification pending",publicationCountry:"Brazil",languages:["pt","yo"],bookCollection:"ODU_PATAKINES",sourceUrl:"https://books.google.com/books/about/Poesia_divinat%C3%B3ria_de_If%C3%A1.html?id=W4Cr0QEACAAJ",sourceLabel:"Google Books bibliographic record"},
 {id:"ijinle-ohun-enu-ifa",title:"Ìjìnlẹ̀ Ohùn Ẹnu Ifá",author:"Wándé Abímbọ́lá",isbn:"9780690514",publisher:"University Press",publicationCountry:"Nigeria",languages:["yo"],bookCollection:"YORUBA",sourceUrl:"https://libcat.aun.edu.ng/cgi-bin/koha/opac-detail.pl?biblionumber=147953",sourceLabel:"American University of Nigeria library catalog"},
 {id:"sixteen-cowries",title:"Sixteen Cowries: Yoruba Divination from Africa to the New World",author:"William W. Bascom",isbn:"9780253208477",publisher:"Indiana University Press",publicationCountry:"United States",languages:["yo","en"],bookCollection:"HISTORIA_ESTUDIOS",sourceUrl:"https://iupress.org/9780253208477/sixteen-cowries/",sourceLabel:"Publisher product page"},
];
