"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import styles from "./owner.module.css";
import { calculateSupplierDealIntelligence, type SupplierDealInput } from "@/lib/supplier-deal-intelligence";
import { wholesaleBrandReadiness } from "@/lib/wholesale-brand-readiness";
import { scoreSupplierOpportunity } from "@/lib/supplier-opportunity-score";
import { getShopifyOwnerLinks } from "@/lib/shopify-links";
import { assessZeroCapitalCandidate, ZERO_CAPITAL_CUSTOMER_NOTICE_ES, ZERO_CAPITAL_OWNER_RULES } from "@/lib/zero-capital-launch";

type Org = { id: string; name?: string; role?: string };
type Me = { id: string; email: string; is_owner: boolean };
type Dashboard = { products_total?: number; pending_approvals?: number; orders_total?: number; orders_on_hold?: number; revenue_30d?: number; net_profit_30d?: number; autonomy_enabled?: boolean; commerce_release_enabled?: boolean; };
type ReadinessCheck = { id: string; label: string; level: "blocker" | "warning" | "ok"; detail: string; fix?: string };
type Readiness = { ready: boolean; blockers: number; warnings: number; checks: ReadinessCheck[] };
type ShopifyStatus = { connected: boolean; status?: "verified" | "credentials_stale" | "not_configured"; shop: string | null; store_name?: string | null; mode?: "token" | "dev_dashboard" | null; verified_at?: string | null; detail?: string; };
type CatalogProduct = { id: string; title: string; status: string; price: number; cost: number; shopify_id?: number };
type Approval = { id: string; action: string; risk_level: string; status: string; agent_name?: string };
type SupplierProduct = SupplierDealInput & { id:string; name:string; supplier:string; sku?:string; competitorUrl?:string; competitorScannedAt?:string; competitorScanStatus?:string; brandMode?:string; resaleAuthorizationStatus?:string; authorizationReference?:string; inventoryStatus?:string; inventoryVerifiedAt?:string };

export default function BotanicaOwnerOS() {
  const [token, setToken] = useState(""); const [orgId, setOrgId] = useState(""); const [me, setMe] = useState<Me | null>(null); const [dashboard, setDashboard] = useState<Dashboard | null>(null); const [readiness, setReadiness] = useState<Readiness | null>(null); const [shopify, setShopify] = useState<ShopifyStatus>({ connected:false, status:"not_configured", shop:null }); const [products, setProducts] = useState<CatalogProduct[]>([]); const [supplierProducts,setSupplierProducts]=useState<SupplierProduct[]>([]); const [approvals, setApprovals] = useState<Approval[]>([]); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  useEffect(() => { setToken(localStorage.getItem("commerce_os_token") ?? ""); setOrgId(localStorage.getItem("commerce_os_org") ?? ""); }, []);
  const clearSession = useCallback(() => { localStorage.removeItem("commerce_os_token"); localStorage.removeItem("commerce_os_org"); setToken(""); setOrgId(""); setMe(null); }, []);
  const headers = useMemo(() => ({ "Content-Type":"application/json", ...(token ? { Authorization:`Bearer ${token}` } : {}) }), [token]);
  const getJson = useCallback(async (path:string) => { const res=await fetch(path,{headers}); const body=await res.json().catch(()=>({})); if(res.status===401){clearSession();throw new Error("Owner session expired. Sign in again.");} if(!res.ok) throw new Error(body.detail ?? `Request failed (${res.status})`); return body; }, [clearSession,headers]);
  const load = useCallback(async()=>{ if(!token){setLoading(false);return;} setLoading(true);setError(""); try { const [meResp,orgs]=await Promise.all([getJson("/api/auth/me") as Promise<Me>,getJson("/api/orgs") as Promise<Org[]>]); if(!meResp.is_owner){clearSession();throw new Error("Owner access is required for BOTANICA Owner OS.");} const selected=orgs.find(o=>o.id===orgId)??orgs[0]; if(!selected?.id) throw new Error("No organization is available for this owner account."); const oid=selected.id; setMe(meResp);setOrgId(oid);localStorage.setItem("commerce_os_org",oid); const [dash,ready,shop,catalog,pending,supplierCatalog]=await Promise.all([getJson(`/api/orgs/${oid}/dashboard`) as Promise<Dashboard>,getJson(`/api/orgs/${oid}/readiness`) as Promise<Readiness>,getJson(`/api/orgs/${oid}/integrations/shopify`) as Promise<ShopifyStatus>,getJson(`/api/orgs/${oid}/owner-catalog`) as Promise<CatalogProduct[]>,getJson(`/api/orgs/${oid}/approvals`) as Promise<Approval[]>,getJson(`/api/orgs/${oid}/supplier-catalogs`) as Promise<SupplierProduct[]>]); setDashboard(dash);setReadiness(ready);setShopify(shop);setProducts(catalog);setApprovals(pending);setSupplierProducts(supplierCatalog); } catch(e){setError(e instanceof Error?e.message:String(e));} finally{setLoading(false);} },[clearSession,getJson,orgId,token]);
  useEffect(()=>{void load();},[load]);
  const pendingApprovals=approvals.filter(a=>a.status==="pending").length; const managedProducts=products.filter(p=>p.status!=="killed").length;
  const dealRows=useMemo(()=>supplierProducts.map(product=>({product,deal:calculateSupplierDealIntelligence(product),opportunity:scoreSupplierOpportunity(product)})).filter(row=>row.deal.fxReady).sort((a,b)=>b.opportunity.score-a.opportunity.score||b.deal.retailProfitPerSupplierOrderUsd-a.deal.retailProfitPerSupplierOrderUsd),[supplierProducts]);
  const pendingFx=supplierProducts.filter(product=>!calculateSupplierDealIntelligence(product).fxReady).length;const pendingScans=supplierProducts.filter(product=>product.competitorUrl&&!product.competitorScannedAt).length;
  const ownBrandReady=supplierProducts.filter(product=>wholesaleBrandReadiness(product).ready).length;
  const zeroCapitalRows=useMemo(()=>supplierProducts.map(product=>({product,assessment:assessZeroCapitalCandidate(product)})).sort((a,b)=>Number(b.assessment.eligible)-Number(a.assessment.eligible)||b.assessment.cashAfterPurchaseUsd-a.assessment.cashAfterPurchaseUsd),[supplierProducts]);
  const zeroCapitalReady=zeroCapitalRows.filter(row=>row.assessment.eligible).length;
  const shopifyLabel=shopify.connected?`Shopify verified · ${shopify.shop}`:shopify.status==="credentials_stale"?`Shopify credentials need attention · ${shopify.shop??"store unresolved"}`:"Shopify not configured";
  const shopifyMetric=shopify.connected?"VERIFIED":shopify.status==="credentials_stale"?"STALE":"OFF"; const shopifyNote=shopify.connected?`${shopify.store_name??shopify.shop??"Shopify"}${shopify.verified_at?` · checked ${new Date(shopify.verified_at).toLocaleTimeString()}`:""}`:shopify.detail??shopify.shop??"No Shopify credentials configured";
  const shopifyLinks=getShopifyOwnerLinks(shopify.shop);
  return <main className={styles.shell}><nav className={styles.nav}><a className={styles.brand} href="/store"><span className={styles.mark}>O</span><span className={styles.brandText}><strong>BOTANICA</strong><small>OCHOSI</small></span></a><div className={styles.navLinks}><a className={`${styles.ghost} ${styles.hideMobile}`} href="/owner/directory">Mi directorio</a><a className={`${styles.ghost} ${styles.hideMobile}`} href="/owner/supplier-catalogs">Catálogos</a><a className={`${styles.ghost} ${styles.hideMobile}`} href="/owner/suppliers">Proveedores</a><a className={styles.primary} href="/owner/catalog">Catálogo</a></div></nav><div className={styles.content}>
    <section className={styles.hero}><div className={styles.kicker}>OWNER COMMAND · BOTANICA-FIRST OPERATIONS</div><h1>Owner <em>OS.</em></h1><p>One operating surface for Shopify, catalog governance, Supplier Intelligence, Council decisions, approvals, orders and production readiness. The customer experience and the owner experience share the same BOTANICA OCHOSI visual system.</p><div className={styles.heroActions}><a className={styles.primary} href="/owner/catalog">Manage catalog</a>{shopifyLinks&&<><a className={styles.primary} href={shopifyLinks.storefront} target="_blank" rel="noreferrer">Ver tienda Shopify ↗</a><a className={styles.ghost} href={shopifyLinks.admin} target="_blank" rel="noreferrer">Shopify Admin ↗</a></>}<a className={styles.ghost} href="/owner/suppliers">Review suppliers</a><button className={styles.ghost} onClick={()=>void load()} disabled={loading}>{loading?"Refreshing…":"Refresh intelligence"}</button></div></section>
    {!token&&!loading?<div className={styles.error}><strong>Owner authentication required.</strong><div>Sign in securely to BOTANICA OCHOSI Owner OS.</div><a className={styles.primary} href="/owner/login" style={{marginTop:12}}>Owner sign in</a></div>:null}{error&&<div className={styles.error}><strong>Owner OS requires attention</strong><div>{error}</div>{!token&&<a className={styles.primary} href="/owner/login" style={{marginTop:12}}>Sign in again</a>}</div>}
    <div className={styles.statusStrip}><span className={styles.statusPill}><i className={readiness?.ready?styles.dotLive:styles.dotWarn}/>{readiness?.ready?"Operationally ready":`${readiness?.blockers??0} readiness blocker(s)`}</span><span className={styles.statusPill}><i className={shopify.connected?styles.dotLive:styles.dotWarn}/>{shopifyLabel}</span><span className={styles.statusPill}><i className={styles.dotLocked}/>Autonomous purchasing locked</span><span className={styles.statusPill}><i className={styles.dotLocked}/>Pipeline auto-publish locked</span></div>
    <section className={styles.metricGrid}><Metric label="Readiness" value={readiness?(readiness.ready?"READY":`${readiness.blockers} BLOCKER${readiness.blockers===1?"":"S"}`):"—"} note={`${readiness?.warnings??0} warning(s)`}/><Metric label="Shopify" value={shopifyMetric} note={shopifyNote}/><Metric label="Catalog" value={String(products.length)} note={`${managedProducts} managed records`}/><Metric label="Approvals" value={String(pendingApprovals)} note="pending owner decisions"/><Metric label="Orders" value={String(dashboard?.orders_total??0)} note={`${dashboard?.orders_on_hold??0} on hold`}/><Metric label="30d Net" value={`$${Number(dashboard?.net_profit_30d??0).toFixed(2)}`} note={`Revenue $${Number(dashboard?.revenue_30d??0).toFixed(2)}`}/></section>
    <section className={styles.section}><div className={styles.sectionHead}><div><span>MODO ARRANQUE · SIN RESERVA PROPIA</span><h2>Cada pedido debe financiarse por sí mismo.</h2><p>Este control no publica ni compra automáticamente. Identifica pedidos que podrían cubrir proveedor, comisión de pago, retención fiscal y reserva de reembolso con el cobro del mismo cliente.</p></div><a className={styles.primary} href="/owner/supplier-catalogs">Completar datos</a></div><div className={styles.statusStrip}><span className={styles.statusPill}>{zeroCapitalReady} productos elegibles</span><span className={styles.statusPill}>{zeroCapitalRows.length-zeroCapitalReady} bloqueados</span><span className={styles.statusPill}>MOQ requerido · 1</span><span className={styles.statusPill}>Entrega máxima · 30 días</span><span className={styles.statusPill}>Compras automáticas · bloqueadas</span></div><div className={styles.split}><div className={styles.card}><div className={styles.kicker}>REGLAS DE CAJA</div><h2>Operación financiada por pedido</h2>{ZERO_CAPITAL_OWNER_RULES.map(rule=><div className={styles.check} key={rule}><small>{rule}</small></div>)}</div><div className={styles.card}><div className={styles.kicker}>AVISO DE PREVENTA · ESPAÑOL</div><h2>Texto para el cliente</h2><p>{ZERO_CAPITAL_CUSTOMER_NOTICE_ES}</p><p className={styles.warning}>Debe mostrarse antes del pago junto con una fecha sustentada. No reemplaza políticas legales ni asesoría fiscal.</p></div></div>{!zeroCapitalRows.length?<div className={styles.empty}>Carga productos y datos reales del proveedor para evaluar este modo.</div>:<div className={styles.productList}>{zeroCapitalRows.slice(0,5).map(({product,assessment})=><article className={`${styles.card} ${styles.productRow}`} key={`zero-${product.id}`}><div><div className={styles.kicker}>{assessment.eligible?"ELEGIBLE PARA REVISIÓN OWNER":"BLOQUEADO"} · {product.supplier}</div><h2>{product.name}</h2><div className={styles.productMeta}>Cobro ${assessment.retailPriceUsd.toFixed(2)} · proveedor/MOQ ${assessment.supplierMinimumInvestmentUsd.toFixed(2)} · comisión ${assessment.paymentFeesUsd.toFixed(2)} · retención fiscal ${assessment.taxHoldUsd.toFixed(2)} · reserva reembolso ${assessment.refundHoldUsd.toFixed(2)}</div><div className={assessment.eligible?styles.ok:styles.warning}><strong>{assessment.eligible?`Caja libre estimada $${assessment.cashAfterPurchaseUsd.toFixed(2)}`:assessment.blockers.join(" ")}</strong></div></div><a className={styles.ghost} href="/owner/supplier-catalogs">Revisar producto</a></article>)}</div>}</section>
    <section className={styles.section}><div className={styles.sectionHead}><div><span>INTELIGENCIA AUTÓNOMA DE UTILIDAD</span><h2>Qué comprar, cómo vender y cuándo entregar.</h2><p>Se recalcula automáticamente al abrir o actualizar el Owner Dashboard. El monitor competitivo se ejecuta diariamente; compras, cambios de precio y publicación continúan bloqueados hasta aprobación Owner.</p></div><a className={styles.primary} href="/owner/supplier-catalogs">Ver análisis completo</a></div><div className={styles.statusStrip}><span className={styles.statusPill}>{supplierProducts.length} productos analizados</span><span className={styles.statusPill}>{ownBrandReady} listos como marca propia</span><span className={styles.statusPill}>{supplierProducts.length-ownBrandReady} autorizaciones pendientes</span><span className={styles.statusPill}>{pendingFx} tasas USD pendientes</span><span className={styles.statusPill}>{pendingScans} escaneos pendientes</span></div>{!dealRows.length?<div className={styles.empty}>Añade productos y costos al catálogo secreto para generar recomendaciones.</div>:<div className={styles.productList}>{dealRows.slice(0,5).map(({product,deal,opportunity})=>{const brand=wholesaleBrandReadiness(product);return <article className={`${styles.card} ${styles.productRow}`} key={`deal-${product.id}`}><div><div className={styles.kicker}>{opportunity.verdict} · PUNTAJE {opportunity.score}/100 · {product.supplier} · {product.sku||"SIN SKU"}</div><h2>{product.name}</h2><div className={styles.productMeta}>Costo puesto en almacén <strong>${deal.landedUnitCostUsd.toFixed(2)}</strong> · Retail <strong>${deal.retailPriceUsd.toFixed(2)}</strong> · Utilidad ${deal.retailProfitPerUnitUsd.toFixed(2)}/unidad ({deal.retailMarginPercent.toFixed(2)}%)</div><div className={styles.productMeta}>Mayoreo <strong>${deal.botanicaWholesalePriceUsd.toFixed(2)}</strong> · MOQ botánicas {deal.botanicaOrderQuantity} · utilidad por pedido ${deal.botanicaOrderProfitUsd.toFixed(2)}</div><div className={styles.productMeta}>Comprar mínimo {deal.supplierOrderQuantity} · inversión ${deal.supplierMinimumInvestmentUsd.toFixed(2)} · ROI bruto {opportunity.capitalRoiPercent.toFixed(2)}% · utilidad/día de capital ${opportunity.profitPerCapitalDayUsd.toFixed(2)} · {opportunity.estimatedAnnualCapitalTurns.toFixed(1)} ciclos/año estimados</div><div className={brand.ready?styles.ok:styles.warning}>{brand.ready?"Marca propia autorizada":"Marca propia bloqueada · evidencia pendiente"}{opportunity.blockers.length?` · ${opportunity.blockers.join(" ")}`:""}</div></div><a className={styles.ghost} href={`/owner/profit-calculator?price=${deal.retailPriceUsd}&cost=${deal.supplierUnitCostUsd}&shipping=${deal.inboundShippingUsd}&handling=${deal.handlingUsd}`}>Calcular neto</a></article>})}</div>}</section>
    <section className={styles.section}><div className={styles.sectionHead}><div><span>Operate</span><h2>Run the botanica from one control plane.</h2></div></div><div className={styles.actionGrid}>{shopifyLinks&&<ActionCard title="Tienda Shopify" body={`Abre ${shopify.store_name??shopify.shop??"la tienda conectada"} para revisar la experiencia visible al cliente.`} href={shopifyLinks.storefront} cta="Ver tienda Shopify ↗" external/>}<ActionCard title="Catálogo + Shopify" body="Crea borradores de Shopify, controla el inventario y ejecuta la migración curada de BOTANICA." href="/owner/catalog" cta="Abrir catálogo"/><ActionCard title="Catálogos de proveedores" body="Importa productos, SKU, precios mayoristas, monedas y pedidos mínimos desde CSV o JSON." href="/owner/supplier-catalogs" cta="Importar catálogos"/><ActionCard title="Comunicaciones con proveedores" body="Mensajes bilingües para cuentas mayoristas, reventa, marca privada, cotizaciones, muestras e importación." href="/owner/communications" cta="Preparar comunicación"/><ActionCard title="Calculadora de utilidad" body="Evalúa cada producto, pedido o negociación con todos sus costos y margen neto en USD." href="/owner/profit-calculator" cta="Calcular utilidad"/><ActionCard title="Cotizaciones de Accio Work" body="Evalúa las cotizaciones de Alibaba que traes de Accio: MOQ, capital requerido y si son financiables por pedido." href="/owner/accio-sourcing" cta="Evaluar cotización"/><ActionCard title="Buscar proveedores" body="Ejecuta el barrido de proveedores ahora: fabricantes, distribuidores, mayoristas y revendedores para los SKU que faltan." href="/owner/supplier-discovery" cta="Buscar proveedores"/><ActionCard title="Inteligencia de proveedores" body="Registro con prioridad para Miami, Hialeah, Texas, Nigeria y fabricantes internacionales verificados." href="/owner/suppliers" cta="Abrir proveedores"/><ActionCard title="Mi directorio personal" body="Guarda contactos, notas privadas, fabricantes, asesores y próximas acciones solamente para el propietario." href="/owner/directory" cta="Abrir mi directorio"/></div></section>
    <section className={styles.section}><div className={styles.split}><div className={styles.card}><div className={styles.kicker}>READINESS</div><h2>Operational gates</h2>{!readiness?.checks?.length&&<div className={styles.empty}>No readiness evidence loaded.</div>}{readiness?.checks?.map(check=><div key={check.id} className={styles.check}><div className={styles.checkTop}><strong>{check.label}</strong><strong className={styles[check.level]}>{check.level.toUpperCase()}</strong></div><small>{check.detail}</small>{check.fix&&<small className={styles.warning}>{check.fix}</small>}</div>)}</div><div className={styles.card}><div className={styles.kicker}>GOVERNANCE</div><h2>Owner authority</h2><Gate label="Autonomous purchasing" on={false}/><Gate label="Pipeline auto-publish" on={false}/><Gate label="Commerce release" on={dashboard?.commerce_release_enabled===true}/><Gate label="Autonomy master gate" on={dashboard?.autonomy_enabled===true}/><p>Supplier scoring and Council recommendations remain advisory until deterministic hard gates pass. Catalog approval can create a Shopify draft; it never authorizes supplier spending.</p></div></div></section>
    <footer className={styles.footer}><span>Owner: {me?.email??"authentication pending"}</span><span>Secure Owner OS session · BOTANICA OCHOSI</span></footer></div></main>;
}
function Metric({label,value,note}:{label:string;value:string;note:string}){return <div className={styles.card}><div className={styles.metricLabel}>{label}</div><div className={styles.metricValue}>{value}</div><div className={styles.metricNote}>{note}</div></div>;} function ActionCard({title,body,href,cta,external=false}:{title:string;body:string;href:string;cta:string;external?:boolean}){return <div className={styles.card}><h2>{title}</h2><p>{body}</p><a className={styles.primary} href={href} target={external?"_blank":undefined} rel={external?"noreferrer":undefined}>{cta}</a></div>;} function Gate({label,on}:{label:string;on:boolean}){return <div className={styles.gate}><span>{label}</span><strong className={on?styles.ok:undefined}>{on?"ON":"LOCKED"}</strong></div>;}
