"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import styles from "../../owner.module.css";

type RecordRow = {
  candidate_id:string;
  sku:{sku:string;name_es:string;category:string;supplier_id?:string;publish_status:string;unit_cost?:number;landed_cost?:number;retail_price?:number;inventory_qty?:number};
  evidence:Array<{id:string;kind:string;note:string;source_url?:string;verified:boolean;verified_at?:string}>;
  evaluation:{draft_ready:boolean;live_ready:boolean;failures:string[];margin?:{gross_profit:number;margin_pct:number}|null};
  updated_at:string;
};

type Candidate = { candidate_id:string; family:{name_es:string;category:string}; supplier:{name:string}; score:number; evaluation:{failures:string[]} };

const KINDS=["SUPPLIER_TERMS","PRICE","INVENTORY","PROVENANCE","CULTURAL_REVIEW","RIGHTS","IMAGE_RIGHTS","SAFETY"];

export default function VerificationWorkbench(){
  const [token,setToken]=useState(""); const [orgId,setOrgId]=useState(""); const [records,setRecords]=useState<RecordRow[]>([]); const [candidates,setCandidates]=useState<Candidate[]>([]); const [selected,setSelected]=useState(""); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
  const headers=useMemo(()=>({"Content-Type":"application/json",...(token?{Authorization:`Bearer ${token}`}:{})}),[token]);
  useEffect(()=>{setToken(localStorage.getItem("commerce_os_token")??"");setOrgId(localStorage.getItem("commerce_os_org")??"");},[]);
  async function resolveOrg(){if(orgId)return orgId;const r=await fetch("/api/orgs",{headers});if(!r.ok)return"";const a=await r.json();const id=a?.[0]?.id??"";if(id){setOrgId(id);localStorage.setItem("commerce_os_org",id);}return id;}
  async function load(){const oid=await resolveOrg();if(!oid)return;setError("");const [r1,r2]=await Promise.all([fetch(`/api/orgs/${oid}/owner-catalog/verification`,{headers,cache:"no-store"}),fetch(`/api/orgs/${oid}/owner-catalog/candidates`,{headers,cache:"no-store"})]);const b1=await r1.json().catch(()=>({}));const b2=await r2.json().catch(()=>({}));if(!r1.ok||!r2.ok){setError(b1.detail??b2.detail??"Unable to load workbench.");return;}setRecords(b1.records??[]);setCandidates(b2.candidates??[]);if(!selected&&b2.candidates?.[0]?.candidate_id)setSelected(b2.candidates[0].candidate_id);}
  useEffect(()=>{if(token)void load();},[token]);
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");try{const oid=await resolveOrg();const f=new FormData(e.currentTarget);const kind=String(f.get("kind")??"");const commercial:any={};for(const key of ["supplier_url","supplier_sku","unit_cost","shipping_cost","retail_price","inventory_qty"]){const v=String(f.get(key)??"").trim();if(v)commercial[key]=["unit_cost","shipping_cost","retail_price","inventory_qty"].includes(key)?Number(v):v;}const res=await fetch(`/api/orgs/${oid}/owner-catalog/verification`,{method:"POST",headers,body:JSON.stringify({candidate_id:selected,evidence:{kind,source_url:String(f.get("source_url")??""),note:String(f.get("note")??""),verified:f.get("verified")==="on"},commercial})});const body=await res.json().catch(()=>({}));if(!res.ok)throw new Error(body.detail??`Request failed (${res.status})`);e.currentTarget.reset();await load();}catch(err){setError(err instanceof Error?err.message:String(err));}finally{setBusy(false);}}
  const selectedCandidate=candidates.find(c=>c.candidate_id===selected);const selectedRecord=records.find(r=>r.candidate_id===selected);
  return <main className={styles.shell}><nav className={styles.nav}><a className={styles.brand} href="/owner"><span className={styles.mark}>O</span><span className={styles.brandText}><strong>BOTANICA</strong><small>OCHOSI</small></span></a><div className={styles.navLinks}><a className={styles.ghost} href="/owner/catalog/candidates">Candidates</a><a className={styles.primary} href="/owner/catalog/master">Master Catalog</a></div></nav><div className={styles.content}>
    <section className={styles.hero}><div className={styles.kicker}>EVIDENCE · VERIFICATION · FAIL-CLOSED</div><h1>Verification <em>Workbench.</em></h1><p>Adjunta evidencia comercial y cultural por candidato. La evidencia verificada puede mover un SKU de HOLD a READY_FOR_REVIEW; nunca publica automáticamente ni autoriza compras.</p></section>
    {error&&<div className={styles.error}>{error}</div>}
    <div className={styles.statusStrip}><span className={styles.statusPill}>AUTO-PURCHASE LOCKED</span><span className={styles.statusPill}>AUTO-PUBLISH LOCKED</span><span className={styles.statusPill}>OWNER EVIDENCE REQUIRED</span></div>
    <section className={styles.section}><div className={styles.sectionHead}><div><span>CANDIDATE SKU</span><h2>Select sourcing candidate.</h2></div></div><div className={styles.card}><select className={styles.input} value={selected} onChange={e=>setSelected(e.target.value)}>{candidates.map(c=><option key={c.candidate_id} value={c.candidate_id}>{c.family.name_es} · {c.supplier.name}</option>)}</select>{selectedCandidate&&<div className={styles.productMeta}>{selectedCandidate.family.category} · score {selectedCandidate.score} · current blockers {selectedCandidate.evaluation.failures.join(" · ")}</div>}</div></section>
    <section className={styles.section}><div className={styles.sectionHead}><div><span>ADD EVIDENCE</span><h2>Commercial and cultural verification.</h2></div></div><form className={`${styles.card} ${styles.form}`} onSubmit={submit}><select className={styles.input} name="kind">{KINDS.map(k=><option key={k}>{k}</option>)}</select><input className={styles.input} name="source_url" placeholder="Evidence/source URL"/><input className={styles.input} name="supplier_url" placeholder="Verified supplier URL"/><input className={styles.input} name="supplier_sku" placeholder="Supplier SKU"/><input className={styles.input} name="unit_cost" type="number" step="0.01" min="0" placeholder="Unit cost"/><input className={styles.input} name="shipping_cost" type="number" step="0.01" min="0" placeholder="Shipping cost"/><input className={styles.input} name="retail_price" type="number" step="0.01" min="0" placeholder="Retail price"/><input className={styles.input} name="inventory_qty" type="number" min="0" placeholder="Inventory qty"/><textarea className={styles.textarea} name="note" placeholder="Evidence note / what was verified"/><label className={styles.full}><input type="checkbox" name="verified"/> Mark this evidence verified by owner</label><div className={styles.full}><button disabled={!selected||busy} className={styles.primary}>{busy?"Saving…":"Save evidence"}</button></div></form></section>
    {selectedRecord&&<section className={styles.section}><div className={styles.sectionHead}><div><span>VERIFICATION RESULT</span><h2>{selectedRecord.sku.name_es}</h2></div></div><div className={styles.metricGrid}><div className={styles.card}><div className={styles.metricLabel}>Status</div><div className={styles.metricValue}>{selectedRecord.sku.publish_status}</div><div className={styles.metricNote}>never auto-published</div></div><div className={styles.card}><div className={styles.metricLabel}>Draft gate</div><div className={styles.metricValue}>{selectedRecord.evaluation.draft_ready?"PASS":"BLOCKED"}</div><div className={styles.metricNote}>{selectedRecord.evaluation.failures.join(" · ")||"all gates passed"}</div></div><div className={styles.card}><div className={styles.metricLabel}>Margin</div><div className={styles.metricValue}>{selectedRecord.evaluation.margin?`${selectedRecord.evaluation.margin.margin_pct.toFixed(1)}%`:"—"}</div><div className={styles.metricNote}>{selectedRecord.sku.landed_cost!=null?`landed $${selectedRecord.sku.landed_cost.toFixed(2)}`:"landed cost missing"}</div></div><div className={styles.card}><div className={styles.metricLabel}>Evidence</div><div className={styles.metricValue}>{selectedRecord.evidence.filter(e=>e.verified).length}</div><div className={styles.metricNote}>{selectedRecord.evidence.length} total records</div></div></div><div className={styles.productList}>{selectedRecord.evidence.map(ev=><article key={ev.id} className={`${styles.card} ${styles.productRow}`}><div><h2>{ev.kind}</h2><div className={styles.productMeta}>{ev.verified?"VERIFIED":"UNVERIFIED"} · {ev.note||"No note"}</div>{ev.source_url&&<a className={styles.footer} href={ev.source_url} target="_blank" rel="noreferrer">Open evidence ↗</a>}</div></article>)}</div></section>}
    <footer className={styles.footer}><span>BOTANICA OCHOSI · Evidence Workbench</span><a href="/owner/catalog">← Catalog Control</a></footer>
  </div></main>;
}
