"use client";

import styles from "../owner.module.css";

type SpanishBook={title:string;author:string;category:string;isbn:string;format:string;source:string;url:string;availability:string;description:string;status:string};

const spanishBooks:SpanishBook[]=[
 {title:"Cuadernillo espiritual de Ifá",author:"Laura Gaztelu",category:"IFÁ · Práctica · Cuaderno de trabajo",isbn:"9798233847295",format:"eBook · Castellano",source:"Casa del Libro",url:"https://www.casadellibro.com/ebook-cuadernillo-espiritual-de-ifa-ebook/9798233847295/18088434",availability:"Edición 2026 listada por reseller",description:"Cuaderno práctico en español orientado a reflexión, estudio y aplicación personal dentro de una perspectiva contemporánea de Ifá. Se vende como obra de la autora y no como doctrina universal ni sustituto de formación iniciática.",status:"COMERCIAL · VERIFICAR COSTO RESELLER"},
 {title:"Los Meyi",author:"Rogelio Gómez · Bertha Hernández",category:"IFÁ · Meyi · Historias · Cuba",isbn:"9789597230557",format:"eBook · Castellano",source:"Casa del Libro",url:"https://www.casadellibro.com/ebook-los-meyi-ebook/9789597230557/5290785",availability:"Edición digital listada",description:"Obra en castellano que reúne historias vinculadas a la tradición oral y libretas conservadas de sacerdotes de Ifá, con énfasis en memoria cultural, raíces cubanas y tradición yoruba.",status:"COMERCIAL · DERECHOS/RESELLER"},
 {title:"Las alegorías de Olodumares",author:"Valentina Porras",category:"OSHA + IFÁ · Filosofía · Memoria cultural",isbn:"9789593140683",format:"eBook · Castellano",source:"Casa del Libro / Ruth Casa Editorial",url:"https://www.casadellibro.com/ebook-las-alegorias-de-olodumares-ebook/9789593140683/17495913",availability:"Edición digital listada",description:"Estudio en español sobre símbolos, mitos, refranes, cantos y memoria cultural presentes en la Regla de Osha y el sistema oracular de Ifá. Se clasifica como literatura cultural y filosófica.",status:"COMERCIAL · VERIFICADO ISBN"},
 {title:"El caracol de Osha, oráculo de Santería",author:"José Francisc Ferrer de Sant Jordi",category:"OSHA · DILOGGÚN · 256 Odus",isbn:"9781445755519",format:"Tapa blanda · Castellano",source:"Casa del Libro",url:"https://latam.casadellibro.com/libro-el-caracol-de-osha-oraculo-de-santeria/9781445755519/13335637",availability:"Edición comercial listada",description:"Guía en castellano presentada por su editor como compilación pedagógica sobre consulta de Osha y referencias a los 256 Odus de Osha e Ifá. Debe venderse como obra del autor, no como manual oficial de BOTANICA OCHOSI.",status:"COMERCIAL · VERIFICADO ISBN"},
 {title:"El gran libro de la Santería",author:"Alejandro E. Delgado Torres",category:"SANTERÍA · Cuba · Referencia",isbn:"9788497342575",format:"Tapa dura · Castellano",source:"Casa del Libro / La Esfera de los Libros",url:"https://www.casadellibro.com/libro-el-gran-libro-de-la-santeria/9788497342575/1010291",availability:"Editorial agotada; disponibilidad por resellers/segunda mano",description:"Referencia general en español sobre Santería y religión yoruba desde la perspectiva del autor. Se mantiene como producto reseller cuando exista ejemplar legítimo disponible.",status:"RESELLER · INVENTARIO VARIABLE"},
 {title:"Manual de conceptos religiosos Yoruba",author:"Baba Ifa Karade",category:"YORUBA · Conceptos · Traducción española",isbn:"9788482450056",format:"Tapa blanda · Castellano",source:"Casa del Libro / Equipo Difusor del Libro",url:"https://www.casadellibro.com/libro-manual-de-conceptos-religiosos-yoruba/9788482450056/473333",availability:"Descatalogado; segunda mano/resellers",description:"Edición en castellano del conocido manual de conceptos religiosos yoruba. Incluye vocabulario y explicaciones generales; se ofrece únicamente mediante copias comerciales legítimas de reseller.",status:"RESELLER · DESCATALOGADO"},
 {title:"Santería yoruba: Magia, culto y sabiduría afroamericana",author:"Olga Roig Ribas",category:"YORUBA · SANTERÍA · Introducción",isbn:"9788488885715",format:"Libro · Español",source:"Fnac / Karma 7",url:"https://www.fnac.es/a4539746/Santeria-yoruba-Magia-culto-y-sabiduria-afroamericana",availability:"Reseller/ocasión según inventario",description:"Introducción en español a la Santería yoruba, sus orishas y el sincretismo descrito por la autora. Producto de literatura general, no material iniciático.",status:"RESELLER · INVENTARIO VARIABLE"},
 {title:"Ordun: Aye yoruba y santería",author:"Arnulfo González Vélez",category:"YORUBA · Historia · Cuba · Santería",isbn:"9788479104290",format:"Libro · Español",source:"Fnac / Humanitas",url:"https://www.fnac.es/a4540916/Ordun-Aye-yoruba-y-santeria",availability:"Ficha comercial verificada; inventario a confirmar",description:"Libro en español sobre historia cultural yoruba, diáspora y práctica religiosa en África y Cuba. Se clasifica como referencia histórica y cultural.",status:"COMERCIAL · VERIFICAR INVENTARIO"},
 {title:"El Monte",author:"Lydia Cabrera",category:"AFROCUBANO · Etnografía · Santería",isbn:"9788490742969",format:"Tapa blanda · Español",source:"Fnac / Editorial Verbum",url:"https://www.fnac.es/a10788112/Lydia-Cabrera-El-Monte",availability:"Edición comercial listada",description:"Clásico de la literatura afrocubana sobre saberes populares, tradiciones, rituales y mitos recopilados en Cuba. Debe presentarse como obra etnográfica e histórica, no como instrucción religiosa oficial.",status:"COMERCIAL · VERIFICADO ISBN"},
 {title:"Cuando la fe escribe el destino",author:"Chowikei Studio",category:"IFÁ · Testimonio · Babalawo",isbn:"9798227392268",format:"eBook · Castellano",source:"Casa del Libro",url:"https://www.casadellibro.com/ebook-cuando-la-fe-escribe-el-destino-ebook/9798227392268/16537803",availability:"Edición digital listada",description:"Narración testimonial en castellano sobre transformación espiritual, religión yoruba y camino de babalawo. Se clasifica como memoria/testimonio, no como corpus doctrinal.",status:"COMERCIAL · VERIFICADO ISBN"},
 {title:"Un vaso de agua y un velo",author:"Oba Olff · Oba Ade Dayo",category:"LUKUMÍ · Espiritismo · Diáspora",isbn:"9798903838356",format:"eBook · Castellano",source:"Casa del Libro / Omidina Productions",url:"https://www.casadellibro.com/ebook-un-vaso-de-agua-y-un-velo-ebook/9798903838356/18028214",availability:"Edición 2026 listada",description:"Obra contemporánea en español sobre espiritismo en un contexto Lukumí de influencia yoruba en Cuba y la diáspora. Se vende como obra de sus autores.",status:"COMERCIAL · VERIFICADO ISBN"}
];

const materials=[
 {category:"Materiales de estudio en español",items:["Cuadernos de estudio de Odù","Índices de Odù y Meyi","Diccionarios Yoruba–Español","Tarjetas didácticas de terminología factual","Guías de pronunciación con audio licenciado","Cuadernos para patakines e itan con contenido propio o licenciado","Bibliografías de Ifá y Lucumí","Guías BOTANICA OCHOSI redactadas originalmente y revisadas"]},
 {category:"Materiales físicos Ifá",items:["Ikin Ifá","Opele Ifá","Opon Ifá","Iroke Ifá","Agere Ifá","Ide Ifá","Caracoles / owo eyo","Bolsas y estuches para herramientas","Componentes no consagrados de reemplazo"]},
 {category:"Literatura por colección",items:["Ifá y Odù","Patakines e itan","Lucumí / Regla de Osha","Santería cubana","Historia afrocubana","Yoruba / Nigeria","Orishas","Diccionarios y lengua Yoruba","Estudios académicos","Memorias y testimonios"]}
];

export default function BibliotecaEspanol(){return <main className={styles.shell}><nav className={styles.nav}><a className={styles.brand} href="/owner"><span className={styles.mark}>O</span><span className={styles.brandText}><strong>BOTANICA</strong><small>OCHOSI</small></span></a><div className={styles.navLinks}><a className={styles.ghost} href="/owner/suppliers">Ifá / Suppliers</a><a className={styles.primary} href="/owner/catalog">Catalog Control</a></div></nav><div className={styles.content}>
<section className={styles.hero}><div className={styles.kicker}>BIBLIOTECA EN ESPAÑOL · IFÁ · LUCUMÍ · YORUBA</div><h1>Literatura <em>en Español.</em></h1><p>El español es el idioma prioritario para la biblioteca comercial de BOTANICA OCHOSI. Cada ficha conserva autor, ISBN, reseller/editorial, disponibilidad y una descripción original. Inglés y Yoruba quedan como idiomas complementarios cuando aporten valor.</p></section>
<div className={styles.statusStrip}><span className={styles.statusPill}>ESPAÑOL · PRIORIDAD #1</span><span className={styles.statusPill}>ISBN · VERIFICADO CUANDO DISPONIBLE</span><span className={styles.statusPill}>RESELLER · INVENTARIO REAL</span><span className={styles.statusPill}>COPYRIGHT · HARD GATE</span></div>
<section className={styles.section}><div className={styles.sectionHead}><div><span>Selección prioritaria</span><h2>Libros y materiales en castellano.</h2></div></div><div className={styles.actionGrid}>{spanishBooks.map(b=><article className={styles.card} key={b.isbn}><div className={styles.kicker}>{b.category} · {b.status}</div><h2>{b.title}</h2><p><strong>{b.author}</strong> · {b.format}</p><p><strong>ISBN:</strong> {b.isbn}</p><p><strong>Fuente:</strong> {b.source}</p><p><strong>Disponibilidad:</strong> {b.availability}</p><div className={styles.productMeta}><div><strong>Descripción:</strong> {b.description}</div></div><a className={styles.ghost} href={b.url} target="_blank" rel="noreferrer">Revisar reseller / editorial</a></article>)}</div></section>
<section className={styles.section}><div className={styles.sectionHead}><div><span>Arquitectura del catálogo</span><h2>Materiales seleccionados por categoría.</h2></div></div><div className={styles.actionGrid}>{materials.map(m=><div className={styles.card} key={m.category}><div className={styles.kicker}>ESPAÑOL FIRST · REVIEW GATE</div><h2>{m.category}</h2><div className={styles.productMeta}>{m.items.map(i=><div key={i}>• {i}</div>)}</div></div>)}</div></section>
<section className={styles.section}><div className={styles.card}><div className={styles.kicker}>POLÍTICA EDITORIAL</div><h2>Vender ediciones legítimas, no copiar contenido protegido.</h2><p>BOTANICA OCHOSI utiliza metadata factual, ISBN, descripciones originales y activos autorizados. No se copian libros completos, capítulos, ebooks, patakines protegidos ni escaneos sin licencia. Las obras agotadas o descatalogadas se ofrecen únicamente cuando un reseller legítimo tenga inventario verificable.</p></div></section>
</div></main>}
