export type WholesaleEvidenceStatus = "PUBLIC_VERIFIED" | "WHOLESALE_VERIFIED_PRICE_PENDING" | "PUBLIC_PRICE_TERMS_PENDING";

export type WholesaleProductEvidence = {
  id: string;
  supplier_id: string;
  supplier_name: string;
  title_es: string;
  title_en: string;
  category: string;
  source_url: string;
  wholesale_only: boolean;
  wholesale_price_usd?: number;
  pack_qty?: number;
  public_price_note?: string;
  inventory_evidence: "IN_STOCK_SIGNAL" | "CATALOG_SIGNAL" | "UNKNOWN";
  evidence_status: WholesaleEvidenceStatus;
  verified_at: string;
  shopify_draft_ready: false;
  required_next_checks: string[];
  notes?: string;
};

/**
 * Public commercial evidence gathered for BOTANICA OCHOSI.
 * These are sourcing candidates, NOT approved inventory.
 * No record may become a Shopify draft until reseller eligibility, current stock,
 * landed cost, image rights, cultural/compliance gates and owner review pass.
 */
export const WHOLESALE_PRODUCT_EVIDENCE: WholesaleProductEvidence[] = [
  {
    id: "masalla-7day-black-box12",
    supplier_id: "distribuidora-mas-alla",
    supplier_name: "Distribuidora Mas Alla",
    title_es: "Velón negro de 7 días · caja de 12",
    title_en: "Black 7-Day Candle · box of 12",
    category: "Velas y Velones",
    source_url: "https://www.botanicamasalla.com/plain-candles-wholesale/",
    wholesale_only: true,
    wholesale_price_usd: 38.99,
    pack_qty: 12,
    public_price_note: "$38.99 sale box price shown publicly; page states each listed product is a box of 12.",
    inventory_evidence: "CATALOG_SIGNAL",
    evidence_status: "PUBLIC_VERIFIED",
    verified_at: "2026-08-10",
    shopify_draft_ready: false,
    required_next_checks: ["CURRENT_STOCK", "ACCOUNT_ELIGIBILITY", "SHIPPING_COST", "IMAGE_RIGHTS", "LANDED_COST", "OWNER_REVIEW"],
  },
  {
    id: "masalla-7day-blue-box12",
    supplier_id: "distribuidora-mas-alla",
    supplier_name: "Distribuidora Mas Alla",
    title_es: "Velón azul de 7 días · caja de 12",
    title_en: "Blue 7-Day Candle · box of 12",
    category: "Velas y Velones",
    source_url: "https://www.botanicamasalla.com/plain-candles-wholesale/",
    wholesale_only: true,
    wholesale_price_usd: 38.99,
    pack_qty: 12,
    inventory_evidence: "CATALOG_SIGNAL",
    evidence_status: "PUBLIC_VERIFIED",
    verified_at: "2026-08-10",
    shopify_draft_ready: false,
    required_next_checks: ["CURRENT_STOCK", "ACCOUNT_ELIGIBILITY", "SHIPPING_COST", "IMAGE_RIGHTS", "LANDED_COST", "OWNER_REVIEW"],
  },
  {
    id: "masalla-7day-green-box12",
    supplier_id: "distribuidora-mas-alla",
    supplier_name: "Distribuidora Mas Alla",
    title_es: "Velón verde de 7 días · caja de 12",
    title_en: "Green 7-Day Candle · box of 12",
    category: "Velas y Velones",
    source_url: "https://www.botanicamasalla.com/plain-candles-wholesale/",
    wholesale_only: true,
    wholesale_price_usd: 38.99,
    pack_qty: 12,
    inventory_evidence: "CATALOG_SIGNAL",
    evidence_status: "PUBLIC_VERIFIED",
    verified_at: "2026-08-10",
    shopify_draft_ready: false,
    required_next_checks: ["CURRENT_STOCK", "ACCOUNT_ELIGIBILITY", "SHIPPING_COST", "IMAGE_RIGHTS", "LANDED_COST", "OWNER_REVIEW"],
  },
  {
    id: "masalla-7day-pink-box12",
    supplier_id: "distribuidora-mas-alla",
    supplier_name: "Distribuidora Mas Alla",
    title_es: "Velón rosado de 7 días · caja de 12",
    title_en: "Pink 7-Day Candle · box of 12",
    category: "Velas y Velones",
    source_url: "https://www.botanicamasalla.com/plain-candles-wholesale/",
    wholesale_only: true,
    wholesale_price_usd: 38.99,
    pack_qty: 12,
    inventory_evidence: "CATALOG_SIGNAL",
    evidence_status: "PUBLIC_VERIFIED",
    verified_at: "2026-08-10",
    shopify_draft_ready: false,
    required_next_checks: ["CURRENT_STOCK", "ACCOUNT_ELIGIBILITY", "SHIPPING_COST", "IMAGE_RIGHTS", "LANDED_COST", "OWNER_REVIEW"],
  },
  {
    id: "masalla-7day-red-box12",
    supplier_id: "distribuidora-mas-alla",
    supplier_name: "Distribuidora Mas Alla",
    title_es: "Velón rojo de 7 días · caja de 12",
    title_en: "Red 7-Day Candle · box of 12",
    category: "Velas y Velones",
    source_url: "https://www.botanicamasalla.com/plain-candles-wholesale/",
    wholesale_only: true,
    wholesale_price_usd: 38.99,
    pack_qty: 12,
    inventory_evidence: "CATALOG_SIGNAL",
    evidence_status: "PUBLIC_VERIFIED",
    verified_at: "2026-08-10",
    shopify_draft_ready: false,
    required_next_checks: ["CURRENT_STOCK", "ACCOUNT_ELIGIBILITY", "SHIPPING_COST", "IMAGE_RIGHTS", "LANDED_COST", "OWNER_REVIEW"],
  },
  {
    id: "oshuns-dressed-7day-candle",
    supplier_id: "oshuns-botanica",
    supplier_name: "Oshuns Botanica",
    title_es: "Veladora preparada de 7 días",
    title_en: "Dressed 7-Day Glass Candle",
    category: "Velas y Velones",
    source_url: "https://oshunsbotanica.com/",
    wholesale_only: false,
    wholesale_price_usd: 4.50,
    pack_qty: 1,
    public_price_note: "Wholesale portal publicly shows $4.50 per candle; account/tier terms still require validation.",
    inventory_evidence: "CATALOG_SIGNAL",
    evidence_status: "PUBLIC_VERIFIED",
    verified_at: "2026-08-10",
    shopify_draft_ready: false,
    required_next_checks: ["WHOLESALE_ACCOUNT_APPROVAL", "CURRENT_STOCK", "FORMULA/CLAIMS_REVIEW", "IMAGE_RIGHTS", "SHIPPING_COST", "OWNER_REVIEW"],
  },
  {
    id: "yoruba-opon-ifa",
    supplier_id: "yoruba-distribuidores",
    supplier_name: "Yoruba Distribuidores LLC",
    title_es: "Pilón / tablero Opon Ifá",
    title_en: "Opon Ifa Divination Board",
    category: "Ifá",
    source_url: "https://yorubadistribuidores.com/product/pilon-tablero-opon-ifa/",
    wholesale_only: true,
    public_price_note: "Wholesale availability is public; usable wholesale price is not published.",
    inventory_evidence: "CATALOG_SIGNAL",
    evidence_status: "WHOLESALE_VERIFIED_PRICE_PENDING",
    verified_at: "2026-08-10",
    shopify_draft_ready: false,
    required_next_checks: ["WHOLESALE_QUOTE", "CURRENT_STOCK", "PROVENANCE", "PRACTITIONER_REVIEW", "IMAGE_RIGHTS", "SHIPPING_COST", "OWNER_REVIEW"],
  },
  {
    id: "yoruba-collar-yemaya",
    supplier_id: "yoruba-distribuidores",
    supplier_name: "Yoruba Distribuidores LLC",
    title_es: "Collar Yemayá azul y blanco con ilde",
    title_en: "Yemaya Blue/White Necklace with Ilde",
    category: "Collares y cuentas",
    source_url: "https://yorubadistribuidores.com/product/collar-yemaya-azul-blanco/",
    wholesale_only: true,
    public_price_note: "Wholesale product page exists; $0.00 display is not treated as a valid price.",
    inventory_evidence: "CATALOG_SIGNAL",
    evidence_status: "WHOLESALE_VERIFIED_PRICE_PENDING",
    verified_at: "2026-08-10",
    shopify_draft_ready: false,
    required_next_checks: ["WHOLESALE_QUOTE", "CURRENT_STOCK", "CONSECRATION/CULTURAL_REVIEW", "IMAGE_RIGHTS", "OWNER_REVIEW"],
  },
  {
    id: "yoruba-colonia-7-potencias",
    supplier_id: "yoruba-distribuidores",
    supplier_name: "Yoruba Distribuidores LLC",
    title_es: "Colonia 7 Potencias · 100 ml",
    title_en: "7 Powers Cologne · 100 ml",
    category: "Colonias y Aguas",
    source_url: "https://yorubadistribuidores.com/product/colonia-7-potencias/",
    wholesale_only: true,
    public_price_note: "Wholesale product page exists; $0.00 display is not treated as a valid price.",
    inventory_evidence: "CATALOG_SIGNAL",
    evidence_status: "WHOLESALE_VERIFIED_PRICE_PENDING",
    verified_at: "2026-08-10",
    shopify_draft_ready: false,
    required_next_checks: ["WHOLESALE_QUOTE", "CURRENT_STOCK", "INGREDIENT/CLAIMS_REVIEW", "IMAGE_RIGHTS", "SHIPPING_RESTRICTIONS", "OWNER_REVIEW"],
  },
  {
    id: "yoruba-colonia-prosperidad",
    supplier_id: "yoruba-distribuidores",
    supplier_name: "Yoruba Distribuidores LLC",
    title_es: "Colonia Prosperidad · 100 ml",
    title_en: "Prosperity Cologne · 100 ml",
    category: "Colonias y Aguas",
    source_url: "https://yorubadistribuidores.com/product/colonia-prosperidad/",
    wholesale_only: true,
    public_price_note: "Wholesale product page exists; $0.00 display is not treated as a valid price.",
    inventory_evidence: "CATALOG_SIGNAL",
    evidence_status: "WHOLESALE_VERIFIED_PRICE_PENDING",
    verified_at: "2026-08-10",
    shopify_draft_ready: false,
    required_next_checks: ["WHOLESALE_QUOTE", "CURRENT_STOCK", "INGREDIENT/CLAIMS_REVIEW", "IMAGE_RIGHTS", "SHIPPING_RESTRICTIONS", "OWNER_REVIEW"],
  },
  {
    id: "soulstar-florida-water-12",
    supplier_id: "soul-star-imports",
    supplier_name: "Soul Star Imports",
    title_es: "Florida Water Murray & Lanman 7.5 oz · paquete de 12",
    title_en: "Florida Water Murray & Lanman 7.5 oz · pack of 12",
    category: "Colonias y Aguas",
    source_url: "https://www.soulstarimports.com/",
    wholesale_only: true,
    public_price_note: "Wholesale catalog and pack-of-12 product are public; price requires login.",
    inventory_evidence: "CATALOG_SIGNAL",
    evidence_status: "WHOLESALE_VERIFIED_PRICE_PENDING",
    verified_at: "2026-08-10",
    shopify_draft_ready: false,
    required_next_checks: ["WHOLESALE_LOGIN_PRICE", "CURRENT_STOCK", "AUTHORIZED_RESALE", "IMAGE_RIGHTS", "SHIPPING_COST", "OWNER_REVIEW"],
  },
  {
    id: "soulstar-palo-santo-sticks",
    supplier_id: "soul-star-imports",
    supplier_name: "Soul Star Imports",
    title_es: "Palitos de Palo Santo",
    title_en: "Palo Santo Sticks",
    category: "Inciensos y Sahumerios",
    source_url: "https://www.soulstarimports.com/",
    wholesale_only: true,
    public_price_note: "Listed as a wholesale best seller; price requires login.",
    inventory_evidence: "CATALOG_SIGNAL",
    evidence_status: "WHOLESALE_VERIFIED_PRICE_PENDING",
    verified_at: "2026-08-10",
    shopify_draft_ready: false,
    required_next_checks: ["WHOLESALE_LOGIN_PRICE", "CURRENT_STOCK", "SPECIES/ORIGIN_PROVENANCE", "IMPORT/COMPLIANCE_REVIEW", "IMAGE_RIGHTS", "OWNER_REVIEW"],
  },
  {
    id: "basonsono-brass-bells",
    supplier_id: "babonsono-imports",
    supplier_name: "Babonsono Imports LLC",
    title_es: "Campanas de latón · catálogo mayorista",
    title_en: "Brass Bells · wholesale catalog",
    category: "Instrumentos y Sonido",
    source_url: "https://www.babonsono.com/",
    wholesale_only: true,
    public_price_note: "B2B catalog confirms brass bells; full SKU pricing requires catalog request. $100 wholesale minimum is published.",
    inventory_evidence: "CATALOG_SIGNAL",
    evidence_status: "WHOLESALE_VERIFIED_PRICE_PENDING",
    verified_at: "2026-08-10",
    shopify_draft_ready: false,
    required_next_checks: ["REQUEST_FULL_CATALOG", "SKU_PRICE", "CURRENT_STOCK", "MATERIAL/ORIGIN", "IMAGE_RIGHTS", "OWNER_REVIEW"],
  },
  {
    id: "basonsono-iron-pots",
    supplier_id: "babonsono-imports",
    supplier_name: "Babonsono Imports LLC",
    title_es: "Calderos de hierro · catálogo mayorista",
    title_en: "Iron Pots · wholesale catalog",
    category: "Recipientes y Altares",
    source_url: "https://www.babonsono.com/",
    wholesale_only: true,
    public_price_note: "B2B catalog confirms iron pots; full SKU pricing requires catalog request. $100 wholesale minimum is published.",
    inventory_evidence: "CATALOG_SIGNAL",
    evidence_status: "WHOLESALE_VERIFIED_PRICE_PENDING",
    verified_at: "2026-08-10",
    shopify_draft_ready: false,
    required_next_checks: ["REQUEST_FULL_CATALOG", "SKU_PRICE", "CURRENT_STOCK", "MATERIAL/ORIGIN", "CULTURAL_REVIEW", "IMAGE_RIGHTS", "OWNER_REVIEW"],
  },
];

export const wholesaleSupplierIds = [...new Set(WHOLESALE_PRODUCT_EVIDENCE.map((item) => item.supplier_id))];
export const publiclyPricedWholesaleProducts = WHOLESALE_PRODUCT_EVIDENCE.filter((item) => typeof item.wholesale_price_usd === "number");
